const string = { type: "string" } as const;
const id = { type: "string", format: "uuid" } as const;
const reference = { type: "object", additionalProperties: false, required: ["kind", "code", "label", "scope", "campusId"], properties: { kind: { type: "string", enum: ["CAMPUS", "PROGRAM", "SCHOLARSHIP", "CAMPAIGN", "TAG"] }, code: { ...string, maxLength: 120 }, label: { ...string, maxLength: 120 }, scope: { type: "string", enum: ["GLOBAL", "CAMPUS"] }, campusId: { ...id, nullable: true }, aliases: { type: "array", maxItems: 20, items: { ...string, maxLength: 120 } } } };
const body = (schema: object): object => ({ required: true, content: { "application/json": { schema } } });
const parameter = (name: string): object => ({ in: "path", name, required: true, schema: id });
const errors = { "400": { description: "Contract or mass assignment refused" }, "401": { description: "Session required" }, "403": { description: "Permission refused (fail closed)" }, "404": { description: "Scoped resource unavailable" }, "409": { description: "Version, canonical collision, or in-use scope conflict" }, "422": { description: "REFERENCE_VALUE_UNKNOWN with field only" }, "503": { description: "Reference persistence unavailable; no fallback" } };
export const referencePaths = {
  "/references": {
    get: { summary: "List authorized reference definitions; active values only by default", parameters: [{ in: "query", name: "kind", required: true, schema: reference.properties.kind }, { in: "query", name: "campusId", schema: id }, { in: "query", name: "leadId", schema: id }, { in: "query", name: "includeArchived", schema: { type: "boolean" } }], responses: { "200": { description: "Authorized values only. Lecteur requires an already-readable lead context." }, ...errors } },
    post: { summary: "Create one governed definition and append its audit atomically", requestBody: body(reference), responses: { "201": { description: "Definition created" }, ...errors } },
  },
  "/references/{id}": { patch: { summary: "Rename, add immutable aliases, change unused scope, archive or restore a definition; no deletion", parameters: [parameter("id")], requestBody: body({ type: "object", additionalProperties: false, required: ["expectedVersion"], properties: { label: reference.properties.label, aliases: reference.properties.aliases, scope: reference.properties.scope, campusId: reference.properties.campusId, state: { type: "string", enum: ["ACTIVE", "ARCHIVED"] }, expectedVersion: { type: "integer", minimum: 1 } } }), responses: { "200": { description: "Updated definition and incremented version" }, ...errors } } },
  "/references/{id}/availability/{campusId}": {
    get: { summary: "Read current availability and concurrency version within an administered campus", parameters: [parameter("id"), parameter("campusId")], responses: { "200": { description: "Active flag and current version; version 0 for an unconfigured association" }, ...errors } },
    post: { summary: "Configure a global program availability within an authorized campus", parameters: [parameter("id"), parameter("campusId")], requestBody: body({ type: "object", additionalProperties: false, required: ["active", "expectedVersion"], properties: { active: { type: "boolean" }, expectedVersion: { type: "integer", minimum: 0 } } }), responses: { "201": { description: "Availability and version; 0 denotes a new association" }, ...errors } },
  },
  "/references/legacy-inventory": { post: { summary: "Explicit Super Admin inventory: preserve unknown distinct historical strings as immutable LEGACY entries; no Lead rewrite", requestBody: body({ type: "object", additionalProperties: false }), responses: { "201": { description: "Created count only; idempotent inventory" }, ...errors } } },
  "/leads/{leadId}/tags": {
    get: { summary: "Read attached tags (including archives), lead version and server-calculated canAssign", parameters: [parameter("leadId")], responses: { "200": { description: "Authorized lead tags" }, ...errors } },
    patch: { summary: "Replace tags with ownership/campus, optimistic concurrency and idempotency; append timeline and audit in the same transaction", parameters: [parameter("leadId")], requestBody: body({ type: "object", additionalProperties: false, required: ["tagIds", "expectedVersion", "idempotencyKey"], properties: { tagIds: { type: "array", maxItems: 30, uniqueItems: true, items: id }, expectedVersion: { type: "integer", minimum: 1 }, idempotencyKey: { ...string, minLength: 8, maxLength: 80 } } }), responses: { "200": { description: "Committed tag identifiers and new version" }, ...errors } },
  },
};
