"use client";

import React, { useEffect, useRef, useState } from "react";
import { PageHeader } from "../../_components/ui/page-header";
import { cutoverAttempt, cutoverCan, cutoverFailure, cutoverFreezeAtT0, cutoverId, cutoverLimitLabels, cutoverLocalInstant, cutoverRequest, cutoverStateLabels, cutoverZone,
  type CutoverContext, type CutoverManifest, type CutoverSubmission } from "./cutover-client";
import { CutoverCatchup } from "./cutover-catchup";

export function CutoverWorkspace({ initialManifestId, initialPackageId }: Readonly<{ initialManifestId?: string; initialPackageId?: string }>): React.JSX.Element {
  const [context, setContext] = useState<CutoverContext | null>(null), [manifest, setManifest] = useState<CutoverManifest | null>(null);
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [error, setError] = useState(""), [feedback, setFeedback] = useState("");
  const [resumeId, setResumeId] = useState(initialManifestId ?? ""), [page, setPage] = useState(0), [reason, setReason] = useState("");
  const lock = useRef(false), attempts = useRef(new Map<string, { payload: string; key: string }>());
  async function read(id: string): Promise<void> { const current = await cutoverRequest<CutoverManifest>(`/manifests/${encodeURIComponent(id)}`); setManifest(current); setResumeId(current.id); }
  useEffect(() => {
    let active = true;
    void cutoverRequest<CutoverContext>("/context").then(async (value) => {
      if (!active) return; setContext(value);
      if (initialManifestId) { const current = await cutoverRequest<CutoverManifest>(`/manifests/${encodeURIComponent(initialManifestId)}`); if (active) setManifest(current); }
    }).catch((failure: unknown) => { if (active) setError(cutoverFailure(failure)); }).finally(() => { if (active) setLoading(false); });
    return (): void => { active = false; };
  }, [initialManifestId]);
  async function perform(operation: () => Promise<void>): Promise<void> {
    if (lock.current) return; lock.current = true; setBusy(true); setError(""); setFeedback("");
    try { await operation(); } catch (failure) { setError(cutoverFailure(failure)); } finally { lock.current = false; setBusy(false); }
  }
  function bookmark(id: string): void { const url = new URL(window.location.href); url.search = ""; url.searchParams.set("manifest", id); window.history.replaceState(null, "", url); }
  async function mutate(operation: string, extra: object = {}): Promise<void> {
    if (!manifest) return; const body = { expectedVersion: manifest.version, ...extra };
    await cutoverRequest(`/manifests/${encodeURIComponent(manifest.id)}/${operation}`, { ...body, idempotencyKey: cutoverAttempt(attempts.current, operation, body) });
    await read(manifest.id); setFeedback("Opération enregistrée et état relu depuis le serveur. Aucun flux automatique n’a été activé.");
  }
  if (loading) return <main className="cutover-page"><PageHeader title="Bascule Excel → nouveaux Leads" /><section className="cutover-card" role="status" aria-busy="true">Lecture des droits et du point de reprise…</section></main>;
  if (!context) return <main className="cutover-page"><PageHeader title="Préparation de bascule indisponible" /><section className="cutover-card cutover-error" role="alert"><p>{error || "Les droits actuels n’ont pas pu être relus."}</p><div className="cutover-actions"><a className="secondary-button" href="/">Se reconnecter</a><button className="secondary-button" type="button" onClick={() => window.location.reload()}>Réessayer la lecture</button></div></section></main>;
  const visible = manifest?.submissions.slice(page * 25, (page + 1) * 25) ?? [];
  return <main className="cutover-page" aria-busy={busy}>
    <PageHeader eyebrow="Relation Ynov · continuité du portefeuille" title="Bascule Excel → nouveaux Leads" description="Un gel explicite, une identité durable et une frontière T0 conservée. L’historique Sheets reste hors import." actions={<a className="secondary-button" href="/imports/bootstrap">Retour à l’amorçage Excel</a>} />
    <p className="cutover-notice">Préparation ≠ import effectué. Sheets reste OFF. Aucun T0 réel, import PROD ou invitation n’est déclenché par l’ouverture de cette page. En DEV/STAGING, utilisez uniquement des fixtures synthétiques ou anonymisées.</p>
    {error ? <section className="cutover-error" role="alert"><p>{error}</p>{manifest ? <button type="button" className="secondary-button" disabled={busy} onClick={() => void perform(async () => { await read(manifest.id); setFeedback("État durable relu, sans réexécution. Vérifiez les compteurs et les reçus."); })}>Relire sans réexécuter</button> : null}</section> : null}
    {feedback ? <p role="status" className="cutover-notice">{feedback}</p> : null}
    {!manifest ? <><section className="cutover-card"><h2>Reprendre un manifeste existant</h2><form onSubmit={(event) => { event.preventDefault(); const id = cutoverId(resumeId.trim()); if (id) void perform(async () => { await read(id); bookmark(id); setPage(0); }); }}><label>Identifiant du manifeste<input value={resumeId} disabled={busy} onChange={(event) => setResumeId(event.target.value)} autoComplete="off" maxLength={36} /></label><div className="cutover-actions"><button className="secondary-button" type="submit" disabled={busy || !cutoverId(resumeId.trim())}>Relire le manifeste</button></div></form></section>
      <CutoverCreate context={context} initialPackageId={initialPackageId ?? ""} busy={busy} onCreate={(body) => perform(async () => { const created = await cutoverRequest<CutoverManifest>("/manifests", { ...body, idempotencyKey: cutoverAttempt(attempts.current, "create", body) }); await read(created.id); bookmark(created.id); setFeedback("Manifeste immuable enregistré puis relu. Aucun Lead n’a été créé et Sheets reste désactivé."); })} />
    </> : <>
      <ManifestSummary manifest={manifest} /><section className="cutover-card" aria-labelledby="cutover-control-title"><h2 id="cutover-control-title">Inventaire et réconciliation</h2><p>L’observation relit la source sans créer de Lead. Un chevauchement avec Excel nécessite une décision explicite, jamais un rapprochement automatique par téléphone ou e-mail.</p>
        <div className="cutover-actions"><button type="button" className="secondary-button" disabled={busy} onClick={() => void perform(async () => { await read(manifest.id); setFeedback("État durable relu, sans observation ni import supplémentaire."); })}>Actualiser sans exécuter</button><button type="button" className="secondary-button" disabled={busy || manifest.state === "SUSPENDED" || !cutoverCan(manifest, "canObserve")} onClick={() => void perform(() => mutate("observe"))}>Observer la source désactivée</button><button type="button" className="primary-button" disabled={busy || manifest.state === "SUSPENDED" || !manifest.observedAt || !cutoverCan(manifest, "canReconcile")} onClick={() => void perform(() => mutate("reconcile"))}>Vérifier la réconciliation</button></div>
        <dl className="cutover-counts">{Object.entries({ "Occurrences conservées": manifest.counts.total, "Historique exclu avant T0": manifest.counts.excludedPreT0, "Arrivées à partir de T0": manifest.counts.backlog, "Chevauchements à décider": manifest.counts.overlapReview, "Écarts source": manifest.counts.sourceIssues, "Rattachées à Excel": manifest.counts.linkedBaseline }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{typeof value === "number" ? value : "Non confirmé"}</dd></div>)}</dl>
        <p className="cutover-help">Les écarts source recouvrent d’autres catégories : ne les additionnez pas comme des personnes distinctes. Les fiches et leurs effets ne sont acquis qu’après lecture des reçus.</p>
        <div className="cutover-submissions">{visible.map((entry) => <Submission key={`${entry.key}:${manifest.version}`} entry={entry} manifest={manifest} busy={busy} onDecision={(input) => perform(() => mutate("decisions", input))} />)}{!visible.length ? <p>Aucune soumission conservée sur cette page. Une préparation non observée ne prouve pas que la source est vide.</p> : null}</div>
        <nav className="cutover-actions" aria-label="Pages des soumissions"><button type="button" className="secondary-button" disabled={busy || page === 0} onClick={() => setPage(page - 1)}>Page précédente</button><span>Page {page + 1} · 25 occurrences maximum</span><button type="button" className="secondary-button" disabled={busy || (page + 1) * 25 >= manifest.submissions.length} onClick={() => setPage(page + 1)}>Page suivante</button></nav>
      </section>
      <CutoverCatchup key={`${manifest.id}:${manifest.version}`} manifest={manifest} busy={busy} onConsume={(body) => perform(() => mutate("consume", body))} onCompensate={(body) => perform(() => mutate("compensate", body))} />
      <section className="cutover-card"><h2>Suspension et reprise contrôlées</h2><p>Le journal et les décisions restent conservés. La reprise invalide la qualification précédente : observez et réconciliez à nouveau avant toute exécution.</p><label>Motif conservé<textarea value={reason} maxLength={500} disabled={busy} onChange={(event) => setReason(event.target.value)} /></label><div className="cutover-actions"><button type="button" className="secondary-button" disabled={busy || !reason.trim() || (manifest.state === "SUSPENDED" ? !cutoverCan(manifest, "canResume") : !cutoverCan(manifest, "canSuspend"))} onClick={() => void perform(async () => { await mutate(manifest.state === "SUSPENDED" ? "resume" : "suspend", { reason: reason.trim() }); setReason(""); })}>{manifest.state === "SUSPENDED" ? "Reprendre la préparation" : "Suspendre la préparation"}</button></div></section>
    </>}
  </main>;
}

function CutoverCreate({ context, initialPackageId, busy, onCreate }: Readonly<{ context: CutoverContext; initialPackageId: string; busy: boolean; onCreate: (body: object) => Promise<void> }>): React.JSX.Element {
  const [packageId, setPackageId] = useState(initialPackageId), [connectorId, setConnectorId] = useState("");
  const [t0, setT0] = useState(""), [freeze, setFreeze] = useState(""), [zone, setZone] = useState("Africa/Casablanca"), [arrival, setArrival] = useState("");
  const [evidence, setEvidence] = useState(""), [sheetId, setSheetId] = useState(""), [confirmed, setConfirmed] = useState(false);
  const connector = context.connectors.find((item) => item.id === connectorId), campus = context.campuses.find((item) => item.id === connector?.campusId);
  const valid = Boolean(cutoverId(packageId.trim()) && connector && connector.enabled === false && connector.identityMode === "EXTERNAL_ID" && campus?.canCreate === true && cutoverFreezeAtT0(freeze, t0) && new Date(freeze).valueOf() <= Date.now() && cutoverZone(zone) && arrival.trim() && /^[a-f\d]{64}$/u.test(evidence) && /^\d+$/u.test(sheetId) && Number.isSafeInteger(Number(sheetId)) && confirmed);
  return <section className="cutover-card"><h2>Préparer le gel et la frontière T0</h2><p>Le snapshot Excel final, incluant le delta, doit réellement être gelé et scellé à T0. Pour ce premier lot, le gel et T0 doivent désigner le même instant ; aucune fenêtre intermédiaire n’est qualifiée. L’égalité des valeurs saisies ne prouve pas la couverture réelle du snapshot. Les instants sont explicitement fournis en UTC avec Z, jamais déduits d’un numéro de ligne, d’un horaire local ou d’un décalage fixe.</p><form onSubmit={(event) => { event.preventDefault(); if (valid) void onCreate({ bootstrapPackageId: packageId.trim(), connectorId, t0: new Date(t0).toISOString(), timeZone: zone, excelFrozenAt: new Date(freeze).toISOString(), originalArrivalColumn: arrival.trim(), identityEvidenceSha256: evidence, sourceSheetId: Number(sheetId) }); }}>
    <div className="cutover-fields"><label>Identifiant du lot Excel scellé<input value={packageId} disabled={busy} onChange={(event) => { setPackageId(event.target.value); setConfirmed(false); }} maxLength={36} autoComplete="off" required /></label><label>Connecteur autorisé, désactivé<select value={connectorId} disabled={busy} required onChange={(event) => { setConnectorId(event.target.value); setConfirmed(false); }}><option value="">Choisir la source, sans valeur par défaut</option>{context.connectors.filter((item) => context.campuses.some((value) => value.id === item.campusId && value.canCreate)).map((item) => <option key={item.id} value={item.id} disabled={item.enabled || item.identityMode !== "EXTERNAL_ID"}>{item.label} · {item.enabled ? "Actif : indisponible" : item.identityMode !== "EXTERNAL_ID" ? "Identité durable non qualifiée" : "Désactivé"}</option>)}</select></label>
      <label>Gel final Excel · instant UTC<input value={freeze} disabled={busy} onChange={(event) => { setFreeze(event.target.value); setConfirmed(false); }} placeholder="AAAA-MM-JJThh:mm:ssZ" autoComplete="off" required /><small>Instant du gel réel du snapshot final après delta, identique à T0. Ne choisissez pas une date fictive pour débloquer le formulaire.</small></label><label>Frontière T0 · instant UTC<input value={t0} disabled={busy} onChange={(event) => { setT0(event.target.value); setConfirmed(false); }} placeholder="AAAA-MM-JJThh:mm:ssZ" autoComplete="off" required /><small>Saisissez explicitement le même instant UTC que le gel final. Une arrivée égale à T0 appartient au rattrapage, pas à l’historique exclu.</small></label>
      <label>Fuseau d’affichage IANA<input value={zone} disabled={busy} onChange={(event) => { setZone(event.target.value); setConfirmed(false); }} required maxLength={80} /><small>T0 affiché : {cutoverLocalInstant(t0, zone)}</small></label><label>Identifiant numérique de l’onglet source<input value={sheetId} disabled={busy} onChange={(event) => { setSheetId(event.target.value); setConfirmed(false); }} inputMode="numeric" pattern="[0-9]+" required /><small>Identité de l’onglet Google, pas sa position ni son seul libellé.</small></label>
      <label>Colonne d’arrivée originale UTC<input value={arrival} disabled={busy} onChange={(event) => { setArrival(event.target.value); setConfirmed(false); }} maxLength={200} required /><small>Date source immuable, distincte d’une date de modification.</small></label><label>SHA-256 de la preuve d’identité amont<input value={evidence} disabled={busy} onChange={(event) => { setEvidence(event.target.value); setConfirmed(false); }} maxLength={64} pattern="[a-f0-9]{64}" required /><small>Cette référence déclarée ne constitue pas à elle seule une qualification amont.</small></label></div>
    <label className="cutover-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={(event) => setConfirmed(event.target.checked)} />Les références et instants ont été vérifiés pour cet environnement. Je prépare un manifeste ; je n’active pas le flux Sheets.</label><div className="cutover-actions"><button type="submit" className="primary-button" disabled={busy || !valid}>{busy ? "Vérification en cours…" : "Enregistrer le manifeste préparatoire"}</button></div>
    {!context.campuses.some((item) => item.canCreate) ? <p>Lecture seule : vos droits effectifs ne permettent pas de créer un manifeste dans ce périmètre.</p> : null}
  </form></section>;
}

export function ManifestSummary({ manifest }: Readonly<{ manifest: CutoverManifest }>): React.JSX.Element {
  return <section className="cutover-card" aria-labelledby="cutover-manifest-title">
    <div className="cutover-heading"><h2 id="cutover-manifest-title">Point de reprise durable</h2><span className="cutover-badge">{cutoverStateLabels[manifest.state]}</span></div>
    {manifest.bindingValid === false ? <p className="cutover-error">La source ou le lot lié a évolué. Le journal reste consultable, mais les mutations sont désactivées ; aucune reprise sûre n’est déduite.</p> : null}
    {!cutoverFreezeAtT0(manifest.contract.excelFrozenAt, manifest.contract.t0) ? <p className="cutover-error">La fenêtre entre gel Excel et T0 n’est pas qualifiée par ce premier lot. Le journal est conservé ; aucune réconciliation ni consommation sûre n’est déduite de ces dates déclarées.</p> : null}
    <dl className="cutover-metadata">
      <div><dt>Manifeste · version</dt><dd>{manifest.id} · v{manifest.version}</dd></div><div><dt>T0 UTC · frontière incluse</dt><dd>{manifest.contract.t0}</dd></div><div><dt>Affichage {manifest.contract.timeZone}</dt><dd>{manifest.localT0}</dd></div>
      <div><dt>Gel Excel UTC</dt><dd>{manifest.contract.excelFrozenAt}</dd></div><div><dt>Dernière observation</dt><dd>{manifest.observedAt ?? "Aucune observation acquise"}</dd></div><div><dt>Rapport de réconciliation</dt><dd>{manifest.reportSha256 ?? "Non confirmé"}</dd></div>
      <div><dt>Onglet source · identifiant durable</dt><dd>{manifest.contract.sourceSheetId ?? "Non confirmé"}</dd></div><div><dt>Colonne d’identité amont</dt><dd>{manifest.contract.externalIdColumn}</dd></div><div><dt>Colonne d’arrivée originale</dt><dd>{manifest.contract.originalArrivalColumn}</dd></div>
    </dl>
    <p><a href={`/imports/bootstrap?package=${encodeURIComponent(manifest.contract.bootstrapPackageId)}`}>Relire le lot Excel lié</a> · <a href={`/imports/cutover?manifest=${encodeURIComponent(manifest.id)}`}>Lien durable de reprise</a></p>
    {manifest.suspensionReason ? <p className="cutover-notice">Motif de suspension : {manifest.suspensionReason}</p> : null}
    <ul className="cutover-limits">{manifest.limitations.map((code) => <li key={code}>{cutoverLimitLabels[code] ?? "Réserve serveur non qualifiée : aucune activation n’en est déduite."}</li>)}</ul>
    <p className="cutover-help">{manifest.effectsApplied ? "Des effets ont été enregistrés : examinez leurs reçus avant toute compensation." : "Aucun effet Lead déclaré par ce manifeste."} L’état prêt n’est ni une activation automatique ni une acceptation globale du portefeuille.</p>
  </section>;
}

function Submission({ entry, manifest, busy, onDecision }: Readonly<{ entry: CutoverSubmission; manifest: CutoverManifest; busy: boolean; onDecision: (body: object) => Promise<void> }>): React.JSX.Element {
  const [action, setAction] = useState(""), [target, setTarget] = useState(""), [reason, setReason] = useState("");
  const allowed = cutoverCan(manifest, "canDecide") && manifest.state !== "SUSPENDED" && entry.classification === "BACKLOG" && !entry.issue && !entry.decision;
  const valid = allowed && reason.trim().length > 0 && (action === "KEEP_FOR_CATCHUP" || action === "LINK_BASELINE" && Boolean(cutoverId(target.trim())));
  return <article className="cutover-submission"><div className="cutover-heading"><h3>Soumission {entry.externalId}</h3><span className="cutover-badge">{entry.classification === "EXCLUDED_PRE_T0" ? "Historique exclu" : "À partir de T0"}</span></div><dl className="cutover-metadata"><div><dt>Clé durable</dt><dd>{entry.key}</dd></div><div><dt>Arrivée originale UTC</dt><dd>{entry.originalArrivedAt}</dd></div><div><dt>Décision persistée</dt><dd>{entry.decision === "LINK_BASELINE" ? "Rattachée à une occurrence Excel" : entry.decision === "KEEP_FOR_CATCHUP" ? "Conservée pour rattrapage" : entry.classification === "EXCLUDED_PRE_T0" ? "Exclue par la frontière immuable" : "À qualifier explicitement"}</dd></div></dl>{entry.issue ? <p className="cutover-error">{entry.issue === "SOURCE_CHANGED" ? "La source a changé." : "La soumission a disparu de la source."} La trace originale est conservée ; aucun nouveau Lead n’est déduit de cet écart.</p> : null}{allowed ? <form onSubmit={(event) => { event.preventDefault(); if (valid) void onDecision({ sourceKey: entry.key, action, reason: reason.trim(), ...(action === "LINK_BASELINE" ? { targetBootstrapRowId: target.trim() } : {}) }); }}><div className="cutover-fields"><label>Disposition explicite<select value={action} disabled={busy} onChange={(event) => setAction(event.target.value)} required><option value="">Choisir après rapprochement</option><option value="KEEP_FOR_CATCHUP">Conserver pour le rattrapage</option><option value="LINK_BASELINE">Rattacher à une occurrence Excel acceptée</option></select></label>{action === "LINK_BASELINE" ? <label>Identifiant de l’occurrence Excel acceptée<input value={target} disabled={busy} onChange={(event) => setTarget(event.target.value)} maxLength={36} required /><small>Le serveur contrôle le même lot et la lisibilité de la fiche cible.</small></label> : null}</div><label>Motif du rapprochement<textarea value={reason} disabled={busy} onChange={(event) => setReason(event.target.value)} maxLength={500} required /></label><div className="cutover-actions"><button type="submit" className="secondary-button" disabled={busy || !valid}>Enregistrer la disposition</button></div></form> : null}</article>;
}
