"use client";

import React, { useState } from "react";
import { cutoverCan, cutoverId, type CutoverEffect, type CutoverManifest } from "./cutover-client";

export function CutoverCatchup({ manifest, busy, onConsume, onCompensate }: Readonly<{ manifest: CutoverManifest; busy: boolean; onConsume: (body: object) => Promise<void>; onCompensate: (body: object) => Promise<void> }>): React.JSX.Element {
  const [confirmed, setConfirmed] = useState(false), [limit, setLimit] = useState("25"), [page, setPage] = useState(0);
  const amount = Number(limit), allowed = cutoverCan(manifest, "canConsume") && manifest.state === "READY_FOR_CATCHUP" && Number.isSafeInteger(amount) && amount >= 1 && amount <= 25;
  const effects = manifest.effects ?? [], visible = effects.slice(page * 25, (page + 1) * 25);
  return <section className="cutover-card" aria-labelledby="cutover-catchup-title"><h2 id="cutover-catchup-title">Rattrapage manuel et reçus</h2>
    <p>Un clic traite un bloc de 25 soumissions maximum. Aucune boucle automatique ne poursuit le lot. Après interruption ou réponse perdue, relisez ce manifeste et ses reçus ; ne recréez pas la source.</p>
    {manifest.catchup ? <><dl className="cutover-counts">{Object.entries({ "Reçus de traitement": manifest.catchup.total, "Dossiers créés": manifest.catchup.created, "Rattachés à Excel": manifest.catchup.linkedBaseline, "À revoir après traitement": manifest.catchup.review, "Soumissions en attente": manifest.catchup.pending }).map(([label, value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="cutover-notice">{manifest.catchup.complete ? "Le bloc de réconciliation est déclaré complet par le serveur. Cela ne qualifie ni l’activation automatique, ni les prérequis PROD encore ouverts." : "Le rattrapage n’est pas complet ou reste en revue. Aucun succès global n’est déduit des seuls dossiers créés."}</p></> : <p className="cutover-notice">Le serveur ne fournit pas encore de preuve d’exécution du rattrapage. Aucune réussite ni absence de doublon n’en est déduite.</p>}
    {cutoverCan(manifest, "canConsume") ? <form onSubmit={(event) => { event.preventDefault(); if (allowed && confirmed) void onConsume({ limit: amount, confirmed: true }); }}><label>Soumissions maximum pour ce clic<input type="number" min={1} max={25} step={1} value={limit} disabled={busy} onChange={(event) => { setLimit(event.target.value); setConfirmed(false); }} /></label><label className="cutover-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={(event) => setConfirmed(event.target.checked)} />J’autorise uniquement ce bloc borné, après examen du gel, des décisions et de la réconciliation. Le flux automatique Sheets reste désactivé.</label><div className="cutover-actions"><button type="submit" className="primary-button" disabled={busy || !allowed || !confirmed || manifest.catchup?.pending === 0}>{busy ? "Traitement et relecture en cours…" : "Traiter ce bloc de rattrapage"}</button></div></form> : <p className="cutover-help">Le traitement n’est pas autorisé dans l’état ou le périmètre actuel. Une préparation prête ne confère aucun droit supplémentaire.</p>}
    <div className="cutover-submissions">{visible.map((effect) => <CatchupEffect key={effect.id} effect={effect} manifest={manifest} busy={busy} onCompensate={onCompensate} />)}{!effects.length ? <p>Aucun reçu de rattrapage disponible. L’inventaire seul ne prouve pas une création de dossier.</p> : null}</div>
    {effects.length > 25 ? <nav className="cutover-actions" aria-label="Pages des reçus de rattrapage"><button type="button" className="secondary-button" disabled={busy || page === 0} onClick={() => setPage(page - 1)}>Reçus précédents</button><span>Page {page + 1}</span><button type="button" className="secondary-button" disabled={busy || (page + 1) * 25 >= effects.length} onClick={() => setPage(page + 1)}>Reçus suivants</button></nav> : null}
    <p className="cutover-help">La compensation disponible consigne une demande et suspend le manifeste. Elle ne retire ni ne supprime le Lead, ne restaure aucune base et ne réécrit aucun suivi effectué après l’import.</p>
  </section>;
}

function CatchupEffect({ effect, manifest, busy, onCompensate }: Readonly<{ effect: CutoverEffect; manifest: CutoverManifest; busy: boolean; onCompensate: (body: object) => Promise<void> }>): React.JSX.Element {
  const [reason, setReason] = useState(""), [confirmed, setConfirmed] = useState(false);
  const canRequest = cutoverCan(manifest, "canCompensate") && effect.outcome === "CREATED" && effect.leadVisible && !effect.compensationStatus;
  const link = effect.leadVisible && effect.leadId ? cutoverId(effect.leadId) : undefined;
  return <article className="cutover-submission"><div className="cutover-heading"><h3>Reçu {effect.id}</h3><span className="cutover-badge">{effect.outcome === "CREATED" ? "Dossier créé" : effect.outcome === "LINKED_BASELINE" ? "Rapprochement Excel conservé" : "En revue · pas de création acquise"}</span></div><dl className="cutover-metadata"><div><dt>Soumission durable</dt><dd>{effect.sourceKey}</dd></div><div><dt>Traitement enregistré</dt><dd>{effect.createdAt}</dd></div><div><dt>Dossier cible</dt><dd>{link ? <a href={`/leads/${encodeURIComponent(link)}`}>Ouvrir la fiche autorisée</a> : "Fiche non visible ou non créée dans ce périmètre"}</dd></div></dl>
    {effect.reason ? <p>Motif conservé : {effect.reason}</p> : null}
    {effect.compensationStatus ? <div className="cutover-notice"><p>{effect.compensationStatus === "BLOCKED_DOWNSTREAM" ? "Compensation refusée : des écritures ultérieures empêchent un retour automatique sûr." : "Demande de compensation enregistrée ; aucune compensation n’est appliquée."}</p><p>Le Lead et son historique sont conservés. Motif : {effect.compensationReason ?? "Non communiqué"}</p></div> : null}
    {canRequest ? <form onSubmit={(event) => { event.preventDefault(); if (reason.trim() && confirmed) void onCompensate({ sourceKey: effect.sourceKey, reason: reason.trim(), confirmed: true }); }}><label>Motif de demande de compensation<textarea value={reason} disabled={busy} maxLength={500} onChange={(event) => { setReason(event.target.value); setConfirmed(false); }} required /></label><label className="cutover-check"><input type="checkbox" checked={confirmed} disabled={busy} onChange={(event) => setConfirmed(event.target.checked)} />Je demande l’examen d’une compensation et la suspension du manifeste. Je comprends qu’aucun Lead ne sera retiré automatiquement.</label><div className="cutover-actions"><button type="submit" className="secondary-button" disabled={busy || !reason.trim() || !confirmed}>Consigner la demande et suspendre</button></div></form> : null}
  </article>;
}
