"use client";
import { StatusBadge } from "../../_components/ui/status-badge";
import { changeLabel, permissionLabel, reasonLabel, restrictionLabel, scopeLabels, type Explanation, type Preview, type Version } from "./permission-types";
export function ChangePreview({ preview }: { preview: Preview }): React.JSX.Element {
  const sensitive = preview.changes.filter((change) => change.sensitive).length;
  const widening = preview.changes.filter((change) => change.widening).length;
  return <section className="panel permission-preview" aria-label="Aperçu des modifications"><div className="permission-section-heading"><div><p className="eyebrow">Validation serveur</p><h2>Aperçu avant enregistrement</h2><p>{preview.affectedUsers} utilisateurs potentiellement concernés · version actuelle {preview.expectedVersion} · aucune modification enregistrée à cette étape.</p></div><StatusBadge tone="warning">À confirmer</StatusBadge></div><div className="permission-preview-meta"><StatusBadge tone="neutral">{`${preview.changes.length} changements`}</StatusBadge><StatusBadge tone={widening ? "warning" : "neutral"}>{`${widening} élargissements / changements de ressources`}</StatusBadge><StatusBadge tone={sensitive ? "warning" : "neutral"}>{`${sensitive} actions sensibles`}</StatusBadge></div><p className="permission-help">Un ajout peut ouvrir l’accès ; un retrait sur ce rôle ne supprime pas les droits apportés par les autres rôles. Les plafonds et les règles métier continuent de s’appliquer.</p><ul className="permission-preview-list">{preview.changes.map((change) => <li key={change.permission}><div><strong>{permissionLabel(change.permission)}</strong><small>{changeLabel(change)}{change.sensitive ? " · action sensible" : ""}</small></div><p><span>Avant</span>{scopeLabels[change.from]}</p><p><span>Après</span>{scopeLabels[change.to]}</p></li>)}</ul>{!preview.changes.length ? <p className="permission-help">Aucun changement.</p> : null}</section>;
}
export function PermissionHistory({ versions, busy, editable, onRestore }: { versions: Version[]; busy: boolean; editable: boolean; onRestore: (version: number) => void }): React.JSX.Element {
  return <details className="panel permission-history"><summary><div><h2>Historique immuable</h2><p>{versions.length} version{versions.length > 1 ? "s" : ""} disponible{versions.length > 1 ? "s" : ""} · Restaurer ajoute une version, sans effacer l’historique.</p></div></summary><p>Une restauration crée une nouvelle version avec les contrôles actuels ; aucune version n’est supprimée.</p>{!versions.length ? <p>Aucune version enregistrée.</p> : <ol className="permission-version-list">{versions.map((version) => <li key={version.number}><div><strong>Version {version.number}</strong> · <time dateTime={version.createdAt}>{new Date(version.createdAt).toLocaleString("fr-FR")}</time><ul className="permission-audits">{version.audits.map((audit, index) => <li key={`${audit.createdAt}-${index}`}>Modification auditée · rôle(s) {audit.actorRoles.join(" + ")} · motif {reasonLabel(audit.reason)}</li>)}</ul></div><button className="secondary-button" disabled={busy || !editable} type="button" onClick={() => onRestore(version.number)}>Restaurer la version {version.number}</button></li>)}</ol>}</details>;
}
export function EffectivePermissions({ explanation }: { explanation: Explanation }): React.JSX.Element {
  return <section className="panel permission-effective"><div className="permission-section-heading"><div><h2>Mes droits effectifs</h2><p>Droits enregistrés de votre compte connecté, indépendants du brouillon.</p></div><StatusBadge tone="info">Compte connecté</StatusBadge></div><p className="permission-help">{explanation.businessRules}</p><ul className="permission-list permission-effective-list">{explanation.permissions.map((item) => <li key={item.permission}><div><div className="permission-row-title"><strong>{permissionLabel(item.permission)}</strong><StatusBadge tone={item.allowed ? "success" : "neutral"}>{item.allowed ? "Autorisé" : "Refusé"}</StatusBadge></div>{item.restriction ? <p className="permission-help">Cause : {restrictionLabel(item.restriction)}</p> : null}<ul className="permission-effective-sources">{item.sources.map((source) => <li key={source.role}><strong>{source.role}</strong> : droit du rôle {scopeLabels[source.sourceScope]} · plafond global {scopeLabels[source.globalCeiling]} · plafond campus {scopeLabels[source.campusCeiling]} · adaptation campus {scopeLabels[source.campusGrant]} · {source.allowed ? "autorise l’action" : "n’autorise pas l’action"}{source.restriction ? ` · ${restrictionLabel(source.restriction)}` : ""}</li>)}</ul></div></li>)}</ul>{!explanation.permissions.length ? <p className="permission-help">Aucune capacité retournée pour ce contexte.</p> : null}</section>;
}
