"use client";
import { changeLabel, scopeLabels, type Explanation, type Preview, type Version } from "./permission-types";
export function ChangePreview({ preview }: { preview: Preview }): React.JSX.Element {
  return <section className="panel" aria-label="Aperçu des modifications"><h2>Aperçu avant enregistrement</h2><p>{preview.affectedUsers} utilisateurs potentiellement concernés · v{preview.expectedVersion} · aucune mutation effectuée.</p><ul>{preview.changes.map((change) => <li key={change.permission}><strong>{changeLabel(change)} — {change.permission}</strong> : {scopeLabels[change.from]} → {scopeLabels[change.to]}{change.sensitive ? " · sensible" : ""}</li>)}</ul>{!preview.changes.length ? <p>Aucun changement.</p> : null}</section>;
}
export function PermissionHistory({ versions, busy, editable, onRestore }: { versions: Version[]; busy: boolean; editable: boolean; onRestore: (version: number) => void }): React.JSX.Element {
  return <section className="panel"><h2>Historique immuable</h2><p>Une restauration crée une nouvelle version avec les contrôles actuels ; aucune version n’est supprimée.</p>{!versions.length ? <p>Aucune version enregistrée.</p> : <ol>{versions.map((version) => <li key={version.number}><strong>Version {version.number}</strong> · {new Date(version.createdAt).toLocaleString("fr-FR")}<ul>{version.audits.map((audit) => <li key={audit.createdAt}>Auteur technique {audit.actorId} · {audit.actorRoles.join(" + ")} · {audit.reason}</li>)}</ul><button disabled={busy || !editable} type="button" onClick={() => onRestore(version.number)}>Restaurer la version {version.number}</button></li>)}</ol>}</section>;
}
export function EffectivePermissions({ explanation }: { explanation: Explanation }): React.JSX.Element {
  return <section className="panel"><h2>Mes permissions effectives</h2><p>{explanation.businessRules}</p><ul className="permission-list">{explanation.permissions.map((item) => <li key={item.permission}><div><strong>{item.permission} — {item.allowed ? "Autorisée par les grants" : "Refusée"}</strong>{item.restriction ? <p>Restriction : {item.restriction}</p> : null}<ul>{item.sources.map((source) => <li key={source.role}>{source.role} : {scopeLabels[source.sourceScope]} · plafond global {scopeLabels[source.globalCeiling]} · plafond campus {scopeLabels[source.campusCeiling]} · grant campus {scopeLabels[source.campusGrant]} · {source.allowed ? "accorde" : "n’accorde pas"}{source.restriction ? ` · ${source.restriction}` : ""}</li>)}</ul></div></li>)}</ul></section>;
}
