import { HISTORICAL_SHEETS, IMPORT_FIELDS } from "./bootstrap-import.contract.js";

const uuid = { type: "string", format: "uuid" };
const key = { type: "string", pattern: "^[a-zA-Z0-9][a-zA-Z0-9:_-]{2,127}$", maxLength: 128 };
const sha = { type: "string", pattern: "^[a-f0-9]{64}$" };
const column = { type: "string", pattern: "^[A-Z]{1,2}$" };
const version = { type: "integer", minimum: 1 };
const text = { type: "string" };
const reference = (name: string): { $ref: string } => ({ $ref: `#/components/schemas/${name}` });
const jsonBody = (name: string): unknown => ({ required: true, content: { "application/json": { schema: reference(name) } } });
const response = (name: string, description: string): unknown => ({ description, content: { "application/json": { schema: reference(name) } } });
const errors = { "400": { description: "Malformed bounded input or unsafe workbook refused" }, "401": { description: "Session expired/revoked or identity pending activation" }, "403": { description: "Current grants, canonical campus or Lead resource denied" }, "409": { description: "Immutable fingerprint, receipt or optimistic version conflict" }, "422": { description: "Explicit source/reference/annotation resolution required" }, "503": { description: "Transactional persistence unavailable; no success claimed" } };
const id = { name: "id", in: "path", required: true, schema: uuid };
const rowId = { name: "rowId", in: "path", required: true, schema: uuid };
const secured = { security: [{ bearerAuth: [] }] };
const path = "/lead-import/bootstrap";

/** Explicit repository OpenAPI contract, not inferred from TS interfaces. */
export const bootstrapImportSchemas = {
  BootstrapCreate: { type: "object", additionalProperties: false, required: ["fileName", "sizeBytes", "sha256", "campusId", "idempotencyKey"], properties: { fileName: { ...text, maxLength: 180, pattern: "\\.xlsx$" }, sizeBytes: { type: "integer", minimum: 1, maximum: 5242880 }, sha256: sha, campusId: uuid, idempotencyKey: key } },
  BootstrapChunk: { type: "object", additionalProperties: false, required: ["index", "contentBase64", "sha256"], description: "Canonical base64, 1–49152 decoded bytes, exact per-chunk SHA256. Final chunk must match declared total size.", properties: { index: { type: "integer", minimum: 0, maximum: 106 }, contentBase64: { ...text, maxLength: 65536 }, sha256: sha } },
  BootstrapSeal: { type: "object", additionalProperties: false, required: ["sha256"], properties: { sha256: sha } },
  BootstrapSheetMapping: { type: "object", additionalProperties: false, required: ["name", "campaign", "fields", "commentColumns", "ownerAliases"], properties: {
    name: { ...text, enum: HISTORICAL_SHEETS }, campaign: { ...text, minLength: 1, maxLength: 120 }, fields: { type: "object", additionalProperties: false, required: ["firstName", "lastName"], properties: Object.fromEntries(IMPORT_FIELDS.map((name) => [name, column])) },
    commentColumns: { type: "array", uniqueItems: true, maxItems: 10, items: column }, ownerAliases: { type: "object", maxProperties: 120, additionalProperties: uuid },
    excludedColumns: { type: "array", maxItems: 100, items: { type: "object", additionalProperties: false, required: ["column", "reason"], properties: { column, reason: { ...text, minLength: 8, maxLength: 500 } } } },
  } },
  BootstrapMapping: { type: "object", additionalProperties: false, required: ["expectedVersion", "mappingVersion", "sheets"], properties: { expectedVersion: version, mappingVersion: { ...text, enum: ["R8-v1"] }, sheets: { type: "array", minItems: 4, maxItems: 4, items: reference("BootstrapSheetMapping") } } },
  BootstrapCycle: { type: "object", additionalProperties: false, required: ["state", "sourceColumns", "reason"], description: "Provenance only. UNSPECIFIED has no year/evidence. CONFIRMED_TARGET/HISTORICAL_ENROLMENT require consecutive school-year label, >=1 actual non-formula source cell and explicit reason; never derives year from reception or Bac.", properties: { state: { ...text, enum: ["UNSPECIFIED", "CONFIRMED_TARGET", "HISTORICAL_ENROLMENT", "REVIEW"] }, label: { ...text, pattern: "^20[0-9]{2}-20[0-9]{2}$" }, sourceColumns: { type: "array", uniqueItems: true, maxItems: 6, items: column }, reason: { ...text, maxLength: 1000 } } },
  BootstrapAnnotationDecision: { type: "object", additionalProperties: false, required: ["annotationId", "reference", "relationshipId", "action", "reason"], properties: { annotationId: text, reference: text, relationshipId: text, action: { ...text, enum: ["PRESERVE_NOTE", "EXCLUDE"] }, reason: { ...text, minLength: 8, maxLength: 1000 } } },
  BootstrapDecision: { oneOf: [reference("BootstrapEffectDecision"), reference("BootstrapDeferral")] },
  BootstrapDeferral: { type: "object", additionalProperties: false, required: ["expectedVersion", "idempotencyKey", "action", "reason", "confirmed"], description: "Explicit unresolved DEFERRED disposition, not IGNORE/READY/acceptance. Requires current import.view/import.review.resolve and actor-owned idempotency/version. Source/mapping/reasons/versions remain bound in DEFER_ROW receipt and audit. No Lead, notes, provenance or invented identity/owner/status; no overrides, target, cycle or annotation disposition allowed.", properties: { expectedVersion: version, idempotencyKey: key, action: { ...text, enum: ["DEFER"] }, confirmed: { type: "boolean", enum: [true] }, reason: { ...text, minLength: 8, maxLength: 1000 } } },
  BootstrapEffectDecision: { type: "object", additionalProperties: false, required: ["expectedVersion", "idempotencyKey", "action", "reason"], description: "Durable server decision, not yet an import. Before any commit only an explicit audited reopen may supersede it. CREATE requires scoped lead.create (+lead.assign if assigned), motivated status override for missing/milestone source state, and no unresolved scoped contact collision. LINK requires scoped lead.view/lead.edit and preserves existing Lead fields. IGNORE retains the source ledger. Every native annotation needs explicit PRESERVE_NOTE/EXCLUDE; no automatic mirror dedupe.", properties: {
    expectedVersion: version, idempotencyKey: key, action: { ...text, enum: ["CREATE_DOSSIER", "LINK_EXISTING", "IGNORE"] }, targetLeadId: uuid, reason: { ...text, minLength: 8, maxLength: 1000 }, cycle: reference("BootstrapCycle"),
    annotations: { type: "array", maxItems: 100, items: reference("BootstrapAnnotationDecision") }, overrides: { type: "object", additionalProperties: false, properties: Object.fromEntries(["firstName", "lastName", "email", "phone", "program", "educationLevel", "source", "status", "temperature", "ownerId", "campaign"].map((name) => [name, { ...text, maxLength: 254 }])) },
  } },
  BootstrapConfirm: { type: "object", additionalProperties: false, required: ["expectedVersion", "idempotencyKey", "confirmed"], description: "At most 25 READY decisions belonging to the current actor; effects, source notes, audit, receipt and report commit atomically. Replay revalidates current grants and referenced resources. No LeadActivity, closure approval or qualification fabricated.", properties: { expectedVersion: version, idempotencyKey: key, confirmed: { type: "boolean", enum: [true] }, limit: { type: "integer", minimum: 1, maximum: 25, default: 25 } } },
  BootstrapReopen: { type: "object", additionalProperties: false, required: ["expectedVersion", "idempotencyKey", "reason"], description: "Explicit supersession only for the current actor's uncommitted READY or DEFERRED decision. Revalidates import.view/import.review.resolve, version/session/campus. Previous complete decision and fingerprint remain in atomic REOPEN_ROW receipt/audit; old keys are retired. Reopening invalidates bounded qualification. Historical contact/name reservation persists until terminal commit; Sheet reviews never auto-LINK. Committed or ignored rows cannot reopen; a new decision key is required.", properties: { expectedVersion: version, idempotencyKey: key, reason: { ...text, minLength: 8, maxLength: 1000 } } },
  BootstrapPackage: { type: "object", required: ["id", "sha256", "campusId", "state", "version", "counts"], properties: { id: uuid, sha256: sha, campusId: uuid, fileName: text, sizeBytes: { type: "integer" }, state: { ...text, enum: ["UPLOADING", "SEALED", "MAPPED", "PARTIAL", "COMPLETED"] }, version, receivedChunks: { type: "integer" }, expectedChunks: { type: "integer" }, batchId: uuid, replayed: { type: "boolean" }, counts: { type: "object", description: "total/accepted/review/invalid/ignored/pending(READY); no rows auto-approved" }, sheets: { type: "array", items: { type: "object", description: "Physical columns and source row counts, no fake semantic defaults" } } } },
  BootstrapRows: { type: "object", properties: { items: { type: "array", maxItems: 50, items: reference("BootstrapRow") }, nextAfter: { ...uuid, nullable: true } } },
  BootstrapRow: { type: "object", description: "Source values separate from saved decision.resolvedValues/overrides/target/cycle. sourceEvidence preserves physical refs, raw/style/formula metadata (<=100 columns, <=4000 chars/cell). canReopen is actor-owned READY or DEFERRED eligibility, not an authorization grant; server revalidates permissions/version at POST.", properties: { id: uuid, version, state: text, canReopen: { type: "boolean" }, sheet: text, rowNumber: { type: "integer" }, reasons: { type: "array", items: text }, values: { type: "object" }, comments: { type: "array", items: { type: "object" } }, sourceEvidence: { type: "array", maxItems: 100, items: { type: "object" } }, annotations: { type: "array", maxItems: 100, items: { type: "object" } }, decision: { type: "object" }, leadId: uuid } },
  BootstrapContext: { type: "object", description: "Canonical campus-scoped actual capabilities and active available programmes/campaigns/eligible owners; no role expansion." },
  BootstrapReport: { type: "object", description: "Legacy reconciliation.complete and cutoverBlocked remain globally strict; DEFERRED is unresolved there and remains in review totals. Separate boundedReconciliation.qualified requires exhaustive source coverage/dispositions, valid DEFER_ROW receipts and exact terminal effects. Deferred comments/native annotations are retained source evidence, not persisted interactions. Missing usable contacts are counted honestly; reservations are conservative, not absolute identity proof. Only a trusted schemaVersion2 append artifact may bind this inventory; reopening/resolving requires requalification. No production authorization.", properties: { package: reference("BootstrapPackage"), bySheet: { type: "array", items: { type: "object" } }, sourceCoverage: { type: "object" }, reconciliation: { type: "object" }, boundedReconciliation: { type: "object" }, cutoverBlocked: { type: "boolean" }, historicalAcquisitionsExcluded: { type: "boolean" } } },
  BootstrapHistoricalNotes: { type: "object", description: "Requires current lead.view + interaction.view. Historical source author/date remain distinct from importer/import date. Source civil date, cycle and original/replacement owner are provenance only; no new business event." },
};
export const bootstrapImportPaths = {
  [`${path}/context`]: { get: { ...secured, summary: "Current authorized bootstrap capabilities and references", responses: { "200": response("BootstrapContext", "Scoped context"), ...errors } } },
  [`${path}/packages`]: { post: { ...secured, summary: "Create or find immutable campus-bound workbook package", requestBody: jsonBody("BootstrapCreate"), responses: { "201": response("BootstrapPackage", "Durable package or authorized replay"), ...errors } } },
  [`${path}/packages/{id}`]: { get: { ...secured, parameters: [id], summary: "Resume durable bootstrap package", responses: { "200": response("BootstrapPackage", "Current persisted state"), ...errors } } },
  [`${path}/packages/{id}/chunks`]: { post: { ...secured, parameters: [id], summary: "Upload one verified 48KiB decoded chunk", requestBody: jsonBody("BootstrapChunk"), responses: { "201": response("BootstrapPackage", "Chunk stored or same-content replay"), ...errors } } },
  [`${path}/packages/{id}/seal`]: { post: { ...secured, parameters: [id], summary: "Seal snapshot by exact SHA without evaluating formulas or links", requestBody: jsonBody("BootstrapSeal"), responses: { "201": response("BootstrapPackage", "Strict historical four-sheet snapshot sealed"), ...errors } } },
  [`${path}/packages/{id}/mappings`]: { post: { ...secured, parameters: [id], summary: "Persist one explicit R8 mapping and complete review ledger", requestBody: jsonBody("BootstrapMapping"), responses: { "201": response("BootstrapPackage", "Mapping + review rows durable, no Lead mutation"), ...errors } } },
  [`${path}/packages/{id}/rows`]: { get: { ...secured, parameters: [id, { name: "after", in: "query", schema: uuid }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 50, default: 25 } }], summary: "Read scoped source occurrences and durable decisions", responses: { "200": response("BootstrapRows", "Bounded ordered source ledger"), ...errors } } },
  [`${path}/packages/{id}/rows/{rowId}/decision`]: { post: { ...secured, parameters: [id, rowId], summary: "Save explicit historical CREATE/LINK/IGNORE decision", requestBody: jsonBody("BootstrapDecision"), responses: { "201": response("BootstrapRow", "Durable decision, re-readable before confirmation; only explicit audited precommit reopen may supersede it"), ...errors } } },
  [`${path}/packages/{id}/rows/{rowId}/reopen`]: { post: { ...secured, parameters: [id, rowId], summary: "Explicitly reopen an owned READY decision before any commit", requestBody: jsonBody("BootstrapReopen"), responses: { "201": response("BootstrapRow", "Current REVIEW row or authorized exact reopen replay"), ...errors } } },
  [`${path}/packages/{id}/confirm`]: { post: { ...secured, parameters: [id], summary: "Commit bounded owned READY decisions transactionally", requestBody: jsonBody("BootstrapConfirm"), responses: { "201": response("BootstrapPackage", "Atomic effects/report/receipt or authorized exact replay"), ...errors } } },
  [`${path}/packages/{id}/report`]: { get: { ...secured, parameters: [id], summary: "Read source/ledger reconciliation and remaining blockers", responses: { "200": response("BootstrapReport", "Honest counts, not release acceptance"), ...errors } } },
  [`${path}/leads/{leadId}/notes`]: { get: { ...secured, parameters: [{ name: "leadId", in: "path", required: true, schema: uuid }], summary: "Read historical notes and provenance in current Lead scope", responses: { "200": response("BootstrapHistoricalNotes", "Source notes <=1000, provenance <=100 with truncation flags"), ...errors } } },
};
