"use client";

import Link from "next/link";
import React, { useRef, useState } from "react";
import { bootstrapFailure, bootstrapRequest, bootstrapRowLabels, bootstrapRowMotifs, bootstrapWarningLabel, stableBootstrapAttempt, type BootstrapAnnotationDecision, type BootstrapContext, type BootstrapCycleDecision, type BootstrapPackage, type BootstrapRow } from "./bootstrap-client";
import styles from "./bootstrap-styles";

export interface BootstrapRowDecision {
  expectedVersion: number; idempotencyKey: string; action: "CREATE_DOSSIER" | "LINK_EXISTING" | "IGNORE";
  reason: string; targetLeadId?: string; overrides?: Record<string, string>; cycle?: BootstrapCycleDecision; annotations?: BootstrapAnnotationDecision[];
}
interface LeadCandidate { id: string; leadCode: string; firstName: string; lastName: string }
const valueLabels: Readonly<Record<string, string>> = { firstName: "Prénom", lastName: "Nom", email: "Email", phone: "Téléphone", program: "Formation", educationLevel: "Niveau", source: "Source", status: "Statut", temperature: "Température", campaign: "Campagne", ownerId: "Responsable" };
const cycleLabels: Readonly<Record<BootstrapCycleDecision["state"], string>> = { UNSPECIFIED: "Cycle à préciser", CONFIRMED_TARGET: "Candidature confirmée", HISTORICAL_ENROLMENT: "Inscription historique · pas une nouvelle candidature", REVIEW: "Indication de cycle à vérifier" };

export function BootstrapRowReview({ row, source, context, disabled, onDecision, onReopen }: Readonly<{ row: BootstrapRow; source: BootstrapPackage; context: BootstrapContext; disabled: boolean; onDecision: (row: BootstrapRow, decision: BootstrapRowDecision) => Promise<void>; onReopen?: (row: BootstrapRow, input: { expectedVersion: number; idempotencyKey: string; reason: string }) => Promise<void> }>): React.JSX.Element {
  const [action, setAction] = useState<BootstrapRowDecision["action"]>(row.reasons.includes("HISTORICAL_DUPLICATE_STATUS_REVIEW") ? "LINK_EXISTING" : "CREATE_DOSSIER"), [reason, setReason] = useState("");
  const [overrides, setOverrides] = useState<Record<string, string>>({}), [search, setSearch] = useState("");
  const [candidates, setCandidates] = useState<LeadCandidate[]>([]), [targetLeadId, setTargetLeadId] = useState("");
  const [error, setError] = useState(""), [searching, setSearching] = useState(false), [searched, setSearched] = useState(false);
  const [historicalConfirmed, setHistoricalConfirmed] = useState(false), [historicalCells, setHistoricalCells] = useState("");
  const [cycleState, setCycleState] = useState<BootstrapCycleDecision["state"]>("UNSPECIFIED"), [cycleLabel, setCycleLabel] = useState("");
  const [cycleColumns, setCycleColumns] = useState<string[]>([]), [cycleReason, setCycleReason] = useState("");
  const [annotationDecisions, setAnnotationDecisions] = useState<BootstrapAnnotationDecision[]>([]);
  const attempt = useRef<{ payload: string; key: string } | undefined>(undefined);
  const reopenAttempt = useRef<{ payload: string; key: string } | undefined>(undefined);
  const [reopenReason, setReopenReason] = useState("");
  const done = row.state === "ACCEPTED" || row.state === "IGNORED";
  const motifs = bootstrapRowMotifs(row);
  const ownerMissingNeedsChoice = motifs.warnings.some((warning) => warning === "OWNER_MISSING" || warning === "BASELINE_INFORMATION_UNKNOWN:owner") && !Object.hasOwn(overrides, "ownerId");
  const historicalTerminal = action === "CREATE_DOSSIER" && ["ENROLLED", "CLOSED_LOST"].includes(overrides.status ?? "");
  const historicalSourceTerminal = ["ENROLLED", "CLOSED_LOST"].includes(row.values.status ?? "");
  const statusResolutionRequired = historicalSourceTerminal || row.reasons.some((reason) => reason === "STATUS_MISSING_REVIEW" || reason === "HISTORICAL_MILESTONE_STATUS_REVIEW");
  const duplicateSource = row.reasons.includes("HISTORICAL_DUPLICATE_STATUS_REVIEW");
  const emailOmitted = Object.hasOwn(overrides, "email") && overrides.email === "", phoneOmitted = Object.hasOwn(overrides, "phone") && overrides.phone === "";
  const contactPresent = !!((Object.hasOwn(overrides, "email") ? overrides.email : row.values.email)?.trim() || (Object.hasOwn(overrides, "phone") ? overrides.phone : row.values.phone)?.trim());
  const annotationsQualified = (row.annotations ?? []).every((annotation) => annotationDecisions.some((decision) => decision.annotationId === annotation.annotationId && decision.relationshipId === annotation.relationshipId && decision.reference === annotation.reference && decision.reason.trim().length >= 8 && decision.reason.trim().length <= 500));
  const cellsQualified = /^[A-Z]{1,2}[1-9]\d*(?:\s*,\s*[A-Z]{1,2}[1-9]\d*)*$/.test(historicalCells.trim()) && historicalCells.split(",").every((cell) => Number(cell.trim().replace(/^[A-Z]{1,2}/, "")) === row.rowNumber && row.sourceEvidence?.some((evidence) => evidence.reference === cell.trim() && !evidence.formula && !!evidence.text?.trim()));
  const sourceColumns = source.sheets.find((sheet) => sheet.name === row.sheet)?.columns ?? [];
  const years = /^(20\d{2})-(20\d{2})$/.exec(cycleLabel.trim());
  const cycleYearQualified = !!years && Number(years[2]) === Number(years[1]) + 1;
  const cycleQualified = cycleState === "UNSPECIFIED" || (cycleReason.trim().length >= 8 && cycleReason.trim().length <= 500 && cycleColumns.length > 0 && (cycleYearQualified || (cycleState === "REVIEW" && !cycleLabel.trim())));
  async function findCandidates(): Promise<void> {
    setSearching(true); setError(""); setTargetLeadId(""); setCandidates([]); setSearched(false);
    try {
      const campus = context.campuses.find((item) => item.id === source.campusId);
      if (!campus) throw new Error("campus_unavailable");
      const query = new URLSearchParams({ search: search.trim(), campus: campus.code, page: "1", pageSize: "10" });
      const response = await fetch(`/api/crm/leads?${query}`, { credentials: "same-origin", cache: "no-store", headers: { accept: "application/json" } });
      if (!response.ok) throw new Error("candidate_search_refused");
      const payload = await response.json() as { items?: Array<Record<string, unknown>> };
      if (!Array.isArray(payload.items)) throw new Error("candidate_contract_invalid");
      setCandidates(payload.items.filter((item) => typeof item.id === "string" && typeof item.leadCode === "string").map((item) => ({ id: String(item.id), leadCode: String(item.leadCode), firstName: typeof item.firstName === "string" ? item.firstName : "", lastName: typeof item.lastName === "string" ? item.lastName : "" }))); setSearched(true);
    } catch { setError("Recherche de dossiers indisponible ou refusée. Aucun rattachement automatique n’est réalisé."); }
    finally { setSearching(false); }
  }
  async function save(): Promise<void> {
    setError("");
    if (disabled || row.state !== "REVIEW") return;
    if (action !== "IGNORE" && !annotationsQualified) return;
    if (reason.trim().length < 8 || reason.trim().length > 700) return;
    if (action === "LINK_EXISTING" && !targetLeadId) return;
    if (action === "CREATE_DOSSIER" && (emailOmitted || phoneOmitted) && !contactPresent) return;
    if (action !== "IGNORE" && !cycleQualified) return;
    if (action === "CREATE_DOSSIER" && statusResolutionRequired && !overrides.status) return;
    if (action === "CREATE_DOSSIER" && ownerMissingNeedsChoice) return;
    if (duplicateSource && action === "CREATE_DOSSIER") return;
    if (historicalTerminal && (!historicalConfirmed || !cellsQualified)) return;
    const decisionReason = historicalTerminal ? `${reason.trim()} | Antériorité source qualifiée : ${row.sheet} · ${historicalCells.trim()}. Ce n’est pas une nouvelle clôture ni une approbation actuelle.` : reason.trim();
    if (decisionReason.length > 1000) return;
    const cycle: BootstrapCycleDecision | undefined = cycleState === "UNSPECIFIED" || action === "IGNORE" ? undefined : { state: cycleState, ...(cycleLabel.trim() ? { label: cycleLabel.trim() } : {}), sourceColumns: cycleColumns, reason: cycleReason.trim() };
    const body = { expectedVersion: row.version, action, reason: decisionReason, ...(action === "LINK_EXISTING" ? { targetLeadId } : {}), ...(action === "CREATE_DOSSIER" && Object.keys(overrides).length ? { overrides } : {}), ...(cycle ? { cycle } : {}), ...(action !== "IGNORE" && annotationDecisions.length ? { annotations: annotationDecisions.map((decision) => ({ ...decision, reason: decision.reason.trim() })) } : {}) };
    try { await onDecision(row, { ...body, idempotencyKey: stableBootstrapAttempt(attempt, body) }); }
    catch (failure) { setError(bootstrapFailure(failure)); }
  }
  function override(field: string, value: string): void { setOverrides((current) => { const next = { ...current }; if (value) next[field] = value; else delete next[field]; return next; }); }
  async function reopen(): Promise<void> {
    if (disabled || row.state !== "READY" || !row.canReopen || !onReopen || reopenReason.trim().length < 8 || reopenReason.length > 700) return;
    setError("");
    const body = { expectedVersion: row.version, reason: reopenReason.trim() };
    try { await onReopen(row, { ...body, idempotencyKey: stableBootstrapAttempt(reopenAttempt, body) }); }
    catch (failure) { setError(bootstrapFailure(failure)); }
  }
  const owners = context.owners.filter((item) => item.campusId === source.campusId);
  const programs = context.programs.filter((item) => item.campusId === null || item.campusId === source.campusId);
  return <article className={styles.row} aria-labelledby={`row-${row.id}`}>
    <div className={styles.rowHeader}><h3 id={`row-${row.id}`}>{row.sheet} · ligne {row.rowNumber}</h3><span className={`${styles.badge} ${row.state === "REVIEW" || row.state === "INVALID" ? styles.review : ""}`}>{bootstrapRowLabels[row.state]}</span></div>
    {motifs.blockingReasons.length ? <p className={styles.reason}>Décisions à résoudre pour cette occurrence : {motifs.blockingReasons.join(" · ")}</p> : null}
    {motifs.warnings.length ? <div className={styles.notice}><h4>Informations explicitement inconnues · avertissements serveur</h4><ul>{motifs.warnings.map((warning) => <li key={warning}>{bootstrapWarningLabel(warning)}</li>)}</ul><p>Ces avertissements ne bloquent pas à eux seuls le portefeuille. Ils ne constituent ni une décision automatique ni un reçu d’import ; les autres anomalies et les droits restent vérifiés par le serveur.</p></div> : null}
    {!motifs.classified && row.reasons.length ? <p>Cette API n’a pas fourni la distinction avertissements/décisions. Les motifs restent en revue ; aucune ancienne donnée manquante n’est automatiquement acceptée.</p> : null}
    <h4>Valeurs source prévisualisées</h4><dl className={styles.valueGrid}>{Object.entries(row.values).map(([key, value]) => <div key={key}><dt>{valueLabels[key] ?? key}</dt><dd>{value ?? "Non renseigné / à préciser"}</dd></div>)}</dl>
    <p>Responsable initial : {row.sourceOwner ?? "Non renseigné"} · nouveau responsable : {row.replacementOwner ?? "Non renseigné"}. Cycle à préciser sauf preuve source explicitement qualifiée.</p>
    {row.sourceEvidence?.length ? <details className={styles.mapping}><summary>Cellules exactes du fichier scellé · à lire avant décision</summary><p>Les valeurs brutes, formules et styles sont une preuve source, pas des faits commerciaux automatiquement déduits. Les formules ne sont jamais exécutées.</p>{row.sourceEvidence.map((cell) => <div key={cell.reference}><small>Cellule {cell.reference} · type {cell.type}{cell.formula ? " · valeur calculée en cache, à vérifier" : " · valeur littérale"}</small><p className={styles.sourceText}>{cell.text}</p>{cell.raw !== null && cell.raw !== cell.text ? <p className={styles.sourceText}>Valeur brute : {cell.raw}</p> : null}{cell.formulaText ? <p className={styles.sourceText}>Formule source non exécutée : {cell.formulaText}</p> : null}{cell.style !== undefined && cell.style !== null ? <small>Style source : {typeof cell.style === "string" ? cell.style : JSON.stringify(cell.style)}</small> : null}</div>)}{row.sourceEvidenceTruncated ? <p role="alert">Preuve source tronquée : aucune qualification complète n’est déduite de cet aperçu.</p> : null}</details> : null}
    {row.comments.length ? <details><summary>{row.comments.length} commentaire(s) source à conserver</summary>{row.comments.map((comment) => <div key={comment.column}><small>Cellule {comment.column}{row.rowNumber} · date/auteur source inconnus</small><p className={styles.sourceText}>{comment.text}</p></div>)}</details> : null}
    {row.annotations?.length ? <details className={styles.mapping}><summary>{row.annotations.length} annotation(s) native(s) Excel · disposition explicite requise</summary><p>Ces annotations restent lisibles dans la preuve source. Chaque occurrence, même sur la même cellule ou avec le même texte, reçoit sa propre décision ; aucune interaction actuelle n’est fabriquée et rien n’est importé par défaut.</p>{row.annotations.map((annotation) => <div key={annotation.annotationId}><small>Cellule {annotation.reference} · annotation {annotation.annotationId} · {annotation.format ?? "format source"} · {annotation.author ? `auteur source déclaré : ${annotation.author}` : "auteur source inconnu"} · {annotation.sourceDate ? `horodatage source déclaré : ${annotation.sourceDate}, pas une date d’action CRM` : "date source inconnue"}{annotation.parentAnnotationId ? ` · réponse à l’annotation source ${annotation.parentAnnotationId}` : ""}</small><p className={styles.sourceText}>{annotation.text}</p></div>)}</details> : null}
    {row.leadId ? <Link href={`/leads/${encodeURIComponent(row.leadId)}`} className="secondary-button">Ouvrir le dossier enregistré</Link> : null}
    {row.decision ? <p>Décision persistée : {row.decision.action} · {row.decision.reason}. {row.state === "READY" ? "Elle n’est pas encore un reçu d’import." : ""}</p> : null}
    {row.state === "READY" && row.canReopen && onReopen ? <form onSubmit={(event) => { event.preventDefault(); void reopen(); }} className={styles.form}><p>Réviser uniquement votre décision avant import. La décision précédente reste conservée dans le reçu et l’audit ; aucun dossier déjà importé ne peut être rouvert ici.</p><label>Motif de remise en revue<textarea value={reopenReason} disabled={disabled} minLength={8} maxLength={700} required onChange={(event) => setReopenReason(event.target.value)} /></label><button type="submit" className="secondary-button" disabled={disabled || reopenReason.trim().length < 8}>Remettre ma décision en revue avant import</button></form> : null}
    {row.decision?.targetLeadId ? <p>Dossier cible relu : <Link href={`/leads/${encodeURIComponent(row.decision.targetLeadId)}`}>{row.decision.targetLeadId}</Link>. Son suivi actuel ne sera pas écrasé par la reprise.</p> : null}
    {row.decision?.resolvedValues ? <><h4>Valeurs résolues de la décision enregistrée</h4><dl className={styles.valueGrid}>{Object.entries(row.decision.resolvedValues).map(([key, value]) => <div key={key}><dt>{valueLabels[key] ?? key}</dt><dd>{key === "ownerId" && value ? context.owners.find((item) => item.id === value)?.label ?? value : value ?? "Non renseigné / explicitement non affecté"}</dd></div>)}</dl></> : null}
    {row.decision?.cycle ? <p>Cycle de la décision : {cycleLabels[row.decision.cycle.state]}{row.decision.cycle.label ? ` · ${row.decision.cycle.label}` : ""}. {row.decision.cycle.sourceColumns.length ? `Cellules ${row.decision.cycle.sourceColumns.map((column) => `${column}${row.rowNumber}`).join(", ")}. ` : ""}{row.decision.cycle.reason}</p> : null}
    {row.decision?.cycle?.evidence?.length ? <details className={styles.mapping}><summary>Preuves source du cycle relues depuis le fichier scellé</summary>{row.decision.cycle.evidence.map((evidence) => <div key={evidence.reference}><small>Cellule {evidence.reference}{evidence.formula ? " · cellule calculée, non exécutée et non traitée automatiquement comme un fait" : " · texte littéral source"}</small><p className={styles.sourceText}>{evidence.text}</p></div>)}</details> : null}
    {row.decision?.annotations?.length ? <details className={styles.mapping}><summary>Décisions persistées sur les annotations natives</summary>{row.decision.annotations.map((annotation) => <p key={annotation.annotationId}>{annotation.reference} · annotation {annotation.annotationId} · {annotation.action === "PRESERVE_NOTE" ? "Note historique à conserver" : "Exclusion explicite"} · {annotation.reason}</p>)}</details> : null}
    {!done && row.state === "REVIEW" ? <form className={styles.form} onSubmit={(event) => { event.preventDefault(); void save(); }}>
      <label>Décision explicite<select disabled={disabled} value={action} onChange={(event) => { setAction(event.target.value as BootstrapRowDecision["action"]); setTargetLeadId(""); setHistoricalConfirmed(false); }}><option value="CREATE_DOSSIER" disabled={duplicateSource}>Créer un dossier distinct</option><option value="LINK_EXISTING">Rattacher à un dossier choisi sans écraser son suivi</option><option value="IGNORE">Écarter cette occurrence avec motif</option></select></label>
      {duplicateSource ? <p className={styles.notice}>Le statut source « Doublon » ne permet pas de créer une nouvelle inscription. Rapprochez explicitement un dossier existant autorisé ou écartez l’occurrence avec son motif ; l’antériorité reste conservée.</p> : null}
      {action === "CREATE_DOSSIER" && statusResolutionRequired && !historicalSourceTerminal ? <p className={styles.notice}>Le statut source est absent ou décrit un jalon historique, pas un statut CRM certain. Choisissez explicitement un statut valide et justifiez cette résolution avant de créer un dossier ; aucun statut Prospect n’est choisi automatiquement. Les cellules source restent conservées.</p> : null}
      {action === "CREATE_DOSSIER" ? <><p>Corrections explicites seulement. Les champs absents ou contradictoires ne reçoivent aucune valeur par défaut. Une ancienne inscription n’est pas une nouvelle approbation de clôture.</p><div className={styles.fields}>
        <label>Correction explicite du prénom<input value={overrides.firstName ?? ""} disabled={disabled} maxLength={100} placeholder="Conserver la valeur source" onChange={(event) => override("firstName", event.target.value)} /></label>
        <label>Correction explicite du nom<input value={overrides.lastName ?? ""} disabled={disabled} maxLength={100} placeholder="Conserver la valeur source" onChange={(event) => override("lastName", event.target.value)} /></label>
        <div><label>Correction explicite de l’email<input type="email" value={overrides.email ?? ""} disabled={disabled || emailOmitted} maxLength={254} placeholder="Conserver la valeur source" onChange={(event) => override("email", event.target.value)} /></label><label className={styles.check}><input type="checkbox" checked={emailOmitted} disabled={disabled} onChange={(event) => { if (event.target.checked) setOverrides((current) => ({ ...current, email: "" })); else override("email", ""); }} />Ne pas reprendre l’email source · exclusion explicite motivée</label></div>
        <div><label>Correction explicite du téléphone<input type="tel" value={overrides.phone ?? ""} disabled={disabled || phoneOmitted} maxLength={40} placeholder="Conserver la valeur source" onChange={(event) => override("phone", event.target.value)} /></label><label className={styles.check}><input type="checkbox" checked={phoneOmitted} disabled={disabled} onChange={(event) => { if (event.target.checked) setOverrides((current) => ({ ...current, phone: "" })); else override("phone", ""); }} />Ne pas reprendre le téléphone source · exclusion explicite motivée</label></div>
        <label>Formation validée<select value={overrides.program ?? ""} disabled={disabled} onChange={(event) => override("program", event.target.value)}><option value="">{motifs.warnings.includes("BASELINE_INFORMATION_UNKNOWN:program") ? "À préciser · aucune formation inventée" : "Conserver la valeur source / revue"}</option>{programs.map((item) => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label>
        <label>Niveau validé<select value={overrides.educationLevel ?? ""} disabled={disabled} onChange={(event) => override("educationLevel", event.target.value)}><option value="">{motifs.warnings.includes("BASELINE_INFORMATION_UNKNOWN:educationLevel") ? "À préciser · aucun niveau inventé" : "Conserver la valeur source / revue"}</option>{context.educationLevels.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label>Source validée<select value={overrides.source ?? ""} disabled={disabled} onChange={(event) => override("source", event.target.value)}><option value="">Conserver la valeur source / revue</option>{context.sources.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label>Statut source explicitement qualifié<select value={overrides.status ?? ""} disabled={disabled} required={statusResolutionRequired} onChange={(event) => { override("status", event.target.value); setHistoricalConfirmed(false); }}><option value="">{statusResolutionRequired ? "À qualifier explicitement · aucun statut par défaut" : "Conserver la valeur source / revue"}</option>{context.statuses.map((item) => <option key={item} value={item}>{item === "ENROLLED" ? "Inscrit · antériorité historique qualifiée" : item === "CLOSED_LOST" ? "Sans suite · antériorité historique qualifiée" : item}</option>)}</select></label>
        <label>Température explicitement validée<select value={overrides.temperature ?? ""} disabled={disabled} onChange={(event) => override("temperature", event.target.value)}><option value="">Conserver la valeur source / revue</option><option value="UNEVALUATED">Non évalué</option><option value="COLD">Froid</option><option value="WARM">Tiède</option><option value="HOT">Chaud</option></select></label>
        <label>Responsable actif validé<select value={Object.hasOwn(overrides, "ownerId") && overrides.ownerId === "" ? "__UNASSIGNED" : overrides.ownerId ?? ""} disabled={disabled} onChange={(event) => { if (event.target.value === "__UNASSIGNED") setOverrides((current) => ({ ...current, ownerId: "" })); else override("ownerId", event.target.value); }}><option value="">Conserver le rapprochement source / revue</option><option value="__UNASSIGNED">Conserver explicitement non affecté · motif obligatoire</option>{owners.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}</select></label>
      </div>{historicalTerminal ? <><p className={styles.notice}>Cette reprise conserve un statut historique établi. Elle ne crée aucune demande de clôture, décision de Manager ou inscription nouvelle. Une contradiction « Doublon » reste bloquante pour la création.</p><label>Cellule(s) source établissant l’antériorité · même ligne {row.rowNumber}<input value={historicalCells} disabled={disabled} maxLength={100} placeholder={`Exemple : L${row.rowNumber}, O${row.rowNumber}`} onChange={(event) => { setHistoricalCells(event.target.value.toUpperCase()); setHistoricalConfirmed(false); }} /></label><label className={styles.check}><input type="checkbox" disabled={disabled || !cellsQualified} checked={historicalConfirmed} onChange={(event) => setHistoricalConfirmed(event.target.checked)} />J’ai vérifié ces cellules du fichier scellé : le statut décrit une antériorité certaine, pas une intention, un doublon ou une nouvelle candidature.</label></> : null}</> : null}
      {action === "CREATE_DOSSIER" && (emailOmitted || phoneOmitted) ? <p className={styles.notice}>L’exclusion du contact est explicite et motivée ; sa valeur reste conservée dans le fichier source. Au moins un email ou téléphone valide doit être repris. {contactPresent ? "Sa validité sera vérifiée par le serveur." : "Les deux contacts ne peuvent pas être vidés : corrigez ou conservez le contact utilisable."}</p> : null}
      {action === "LINK_EXISTING" ? <div><label>Rechercher un dossier du campus<input value={search} disabled={disabled || searching} minLength={2} maxLength={100} onChange={(event) => setSearch(event.target.value)} /></label><div className={styles.actions}><button className="secondary-button" type="button" disabled={disabled || searching || search.trim().length < 2} onClick={() => void findCandidates()}>{searching ? "Recherche…" : "Rechercher les dossiers autorisés"}</button></div>
        {searched && !candidates.length ? <p>Aucun dossier accessible trouvé. Précisez votre recherche ; aucune fusion par email ou téléphone n’est supposée.</p> : null}
        {candidates.map((candidate) => <label className={styles.candidate} key={candidate.id}><input type="radio" name={`target-${row.id}`} disabled={disabled} value={candidate.id} checked={candidate.id === targetLeadId} onChange={() => setTargetLeadId(candidate.id)} /><span><strong>{candidate.leadCode}</strong> · {[candidate.firstName, candidate.lastName].filter(Boolean).join(" ")}</span></label>)}
        {candidates.length === 10 ? <p>Dix résultats maximum : précisez la recherche si le bon dossier n’apparaît pas.</p> : null}
      </div> : null}
      {action !== "IGNORE" ? <details className={styles.mapping}><summary>Cycle de candidature · aucune année déduite</summary><p>Sans preuve certaine, le dossier garde « Cycle à préciser ». Ni l’année du bac, ni la date de réception, ni B1/B3/M1 ne définissent une rentrée. Une ancienne inscription et une nouvelle candidature restent distinctes.</p>
        <label>Qualification explicite du cycle<select value={cycleState} disabled={disabled} onChange={(event) => { setCycleState(event.target.value as BootstrapCycleDecision["state"]); setCycleLabel(""); setCycleColumns([]); setCycleReason(""); }}>{Object.entries(cycleLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label>
        {cycleState !== "UNSPECIFIED" ? <><div className={styles.fields}><label>{cycleState === "HISTORICAL_ENROLMENT" ? "Année de l’inscription historique établie" : "Cycle indiqué explicitement dans la source"}<input value={cycleLabel} disabled={disabled} maxLength={9} pattern="20[0-9]{2}-20[0-9]{2}" required={cycleState !== "REVIEW"} placeholder="YYYY-YYYY · deux années successives" onChange={(event) => setCycleLabel(event.target.value)} /></label><label>Motif de qualification du cycle · huit caractères minimum<textarea value={cycleReason} disabled={disabled} minLength={8} maxLength={500} required onChange={(event) => setCycleReason(event.target.value)} /></label></div>
          <p>Cellules source probantes · ligne {row.rowNumber}, six maximum. Le serveur vérifie leur présence dans le fichier scellé ; aucun commentaire n’est modifié. Une cellule vide ou calculée ne prouve pas une rentrée.</p><div className={styles.checkboxes}>{sourceColumns.map((column) => {
            const evidence = row.sourceEvidence?.find((cell) => cell.column === column.letter);
            const available = !!evidence?.text?.trim() && !evidence.formula;
            return <label key={column.letter} className={styles.check}><input type="checkbox" checked={cycleColumns.includes(column.letter)} disabled={disabled || !available || (cycleColumns.length >= 6 && !cycleColumns.includes(column.letter))} onChange={(event) => setCycleColumns((current) => event.target.checked ? [...current, column.letter] : current.filter((value) => value !== column.letter))} />{column.letter}{row.rowNumber} · {column.name || "Sans intitulé en ligne 6"}{!available ? " · vide, calculée ou preuve indisponible" : ""}</label>;
          })}</div>
          {!sourceColumns.length ? <p role="alert">Les colonnes du fichier ne sont pas relues : gardez le cycle à préciser ou actualisez le lot avant une qualification.</p> : null}
          <p>Cette qualification est une métadonnée de provenance, pas une nouvelle décision d’inscription ou de clôture.</p>
        </> : null}
      </details> : null}
      {action !== "IGNORE" && row.annotations?.length ? <fieldset className={styles.mapping}><legend>Disposition de chaque annotation native · aucune valeur par défaut</legend>{row.annotations.map((annotation) => {
        const current = annotationDecisions.find((decision) => decision.annotationId === annotation.annotationId);
        return <div className={styles.fields} key={annotation.annotationId}><label>Action sur l’annotation {annotation.reference} · {annotation.annotationId.slice(0, 8)}<select disabled={disabled} value={current?.action ?? ""} onChange={(event) => {
          const others = annotationDecisions.filter((decision) => decision.annotationId !== annotation.annotationId);
          setAnnotationDecisions(event.target.value ? [...others, { annotationId: annotation.annotationId, reference: annotation.reference, relationshipId: annotation.relationshipId, action: event.target.value as BootstrapAnnotationDecision["action"], reason: current?.reason ?? "" }] : others);
        }}><option value="">À qualifier · aucun import automatique</option><option value="PRESERVE_NOTE">Conserver comme note historique exacte</option><option value="EXCLUDE">Exclure explicitement avec justification</option></select></label><label>Motif de l’annotation {annotation.reference} · {annotation.annotationId.slice(0, 8)} · huit caractères minimum<textarea value={current?.reason ?? ""} disabled={disabled || !current} minLength={8} maxLength={500} required onChange={(event) => setAnnotationDecisions((decisions) => decisions.map((decision) => decision.annotationId === annotation.annotationId ? { ...decision, reason: event.target.value } : decision))} /></label></div>;
      })}<p>Le texte et l’auteur déclaré restent ceux de la source ; aucune date d’échange ni identité CRM n’est inventée. L’exclusion conserve une trace, pas une suppression du fichier scellé.</p></fieldset> : null}
      <label>Justification conservée avec la décision · huit caractères minimum<textarea value={reason} disabled={disabled} minLength={8} maxLength={700} required onChange={(event) => setReason(event.target.value)} /></label>
      <div className={styles.actions}><button type="submit" className="secondary-button" disabled={disabled || reason.trim().length < 8 || (action !== "IGNORE" && (!cycleQualified || !annotationsQualified)) || (action === "LINK_EXISTING" && !targetLeadId) || (action === "CREATE_DOSSIER" && (duplicateSource || ownerMissingNeedsChoice || ((emailOmitted || phoneOmitted) && !contactPresent) || (statusResolutionRequired && !overrides.status))) || (historicalTerminal && (!historicalConfirmed || !cellsQualified))}>Enregistrer la décision, sans exécuter l’import</button></div>
    </form> : null}
    {error ? <p role="alert" className={`${styles.feedback} ${styles.error}`}>{error}</p> : null}
  </article>;
}

export async function persistBootstrapDecision(packageId: string, rowId: string, decision: BootstrapRowDecision): Promise<BootstrapRow> {
  return bootstrapRequest<BootstrapRow>(`/packages/${encodeURIComponent(packageId)}/rows/${encodeURIComponent(rowId)}/decision`, { method: "POST", body: JSON.stringify(decision) });
}
