const uuid = { type: "string", format: "uuid" } as const;
const instant = { type: "string", format: "date-time", description: "Absolute instant with explicit timezone; stored UTC and displayed Africa/Casablanca" } as const;
const key = { type: "string", minLength: 8, maxLength: 128, pattern: "^[A-Za-z0-9_-]+$" } as const;
const version = { type: "integer", minimum: 1 } as const;
const boundedResponses = {
  "200": { description: "Persisted result or immutable authenticated replay" }, "400": { description: "Strict input, time interval or duration refused" },
  "403": { description: "Current session/grant/campus, declared responsible or requester separation refused" }, "404": { description: "Booking/window unavailable" },
  "409": { description: "Slot, version, transition or idempotency conflict; no partial effect" }, "503": { description: "PostgreSQL unavailable; no in-memory fallback" },
} as const;
const idParameter = { name: "id", in: "path", required: true, schema: uuid } as const;
const rangeParameters = [{ name: "from", in: "query", required: true, schema: instant }, { name: "to", in: "query", required: true, schema: instant }] as const;

export const admissionsPaths = {
  "/admissions/context": { get: { summary: "Read current effective Admissions agenda and administration capabilities", description: "canUseAgenda and canManageResponsibilities come from effective persisted grants. Eligible users are active, first-access completed and restricted to manageable campuses. ADMISSIONS remains the Commercial role, not a new global admissions role.", responses: { "200": { description: "Capabilities, own declarations and bounded campus/user reference options" }, "403": boundedResponses["403"], "503": boundedResponses["503"] } } },
  "/admissions/responsibles": {
    get: { summary: "Read active explicitly designated responsible users for an authorized Lead or campus", parameters: [{ name: "leadId", in: "query", schema: uuid }, { name: "campus", in: "query", schema: { type: "string" } }], responses: boundedResponses },
    post: { summary: "Versioned campus-bounded designation or revocation", requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["userId", "campus", "active", "expectedVersion", "idempotencyKey"], properties: { userId: uuid, campus: { type: "string" }, active: { type: "boolean" }, expectedVersion: { type: "integer", minimum: 0 }, idempotencyKey: key } } } } }, responses: { ...boundedResponses, "201": { description: "Designation persisted; no global role or permission granted" } } },
  },
  "/admissions/windows": {
    get: { summary: "Read own manual availability/block windows or an explicitly manageable campus", description: "Never returns another user's private windows to a Commercial.", responses: boundedResponses },
    post: { summary: "Declare a manual UTC availability or private blocked interval", description: "Maximum seven days per window. A block overlapping an existing non-terminal appointment is refused under the shared participant locks.", requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["responsibilityId", "kind", "startsAt", "endsAt", "idempotencyKey"], properties: { responsibilityId: uuid, kind: { type: "string", enum: ["AVAILABLE", "BLOCKED"] }, startsAt: instant, endsAt: instant, idempotencyKey: key } } } } }, responses: { ...boundedResponses, "201": { description: "Window persisted with version, no public calendar or external synchronization" } } },
  },
  "/admissions/windows/{id}": { patch: { summary: "Withdraw one manual window without silently invalidating an active booking", parameters: [idParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["active", "expectedVersion", "idempotencyKey"], properties: { active: { type: "boolean", enum: [false] }, expectedVersion: version, idempotencyKey: key } } } } }, responses: boundedResponses } },
  "/admissions/slots": { get: { summary: "Read only declared free slots for an authorized Lead", description: "Redacted half-open UTC intervals, at most seven days, 15–480 minute duration. Busy titles/reasons and private windows are never returned. Existing appointments and participants occupy the slot. Optional bookingId bounds a responsible's reschedule access and excludes only that reservation.", parameters: [{ name: "leadId", in: "query", required: true, schema: uuid }, { name: "responsibilityId", in: "query", required: true, schema: uuid }, ...rangeParameters, { name: "durationMinutes", in: "query", required: true, schema: { type: "integer", minimum: 15, maximum: 480 } }, { name: "bookingId", in: "query", schema: uuid }], responses: boundedResponses } },
  "/leads/{leadId}/admissions-bookings": { post: { summary: "Request one appointment; the provisional slot is reserved, not approved", description: "All participants share ordered PostgreSQL transaction locks with legacy appointment writers. Availability, blocks, current grants and overlap are rechecked before atomic appointment/request/event/activity/audit/internal-notification/receipt creation. A legacy create targeting a designated Admissions responsible is refused instead of bypassing this flow.", parameters: [{ name: "leadId", in: "path", required: true, schema: uuid }], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["responsibilityId", "startsAt", "durationMinutes", "type", "mode", "idempotencyKey"], properties: { responsibilityId: uuid, startsAt: instant, durationMinutes: { type: "integer", minimum: 15, maximum: 480 }, type: { type: "string" }, mode: { type: "string", enum: ["SUR_SITE", "TELEPHONE", "DISTANCIEL_NON_CONNECTE"] }, participantIds: { type: "array", maxItems: 20, items: uuid }, idempotencyKey: key } } } } }, responses: { ...boundedResponses, "201": { description: "PENDING request and PLANIFIE appointment persisted once; no automatic acceptance" } } } },
  "/admissions/bookings": { get: { summary: "Read own requested/received or explicitly manageable bookings", description: "Campus and audience are constrained in SQL before pagination, then current resource grants are rechecked. Stable startsAt/id ordering, default 50 (maximum 100), hasMore and opaque nextCursor; a bounded authorization scan may return fewer items with hasMore true. Refresh after a schedule change. Minimal booking data does not grant general Lead access. Historical appointment routing exposes Admissions metadata.", parameters: [{ name: "leadId", in: "query", schema: uuid }, { name: "campus", in: "query", schema: { type: "string" } }, { name: "cursor", in: "query", schema: { type: "string", maxLength: 256 } }, { name: "limit", in: "query", schema: { type: "integer", minimum: 1, maximum: 100, default: 50 } }], responses: boundedResponses } },
  "/admissions/bookings/{id}": {
    get: { summary: "Read a bounded booking and server action capabilities", parameters: [idParameter], responses: boundedResponses },
    patch: { summary: "Distinct responsible decision, controlled report/cancel or observed attendance outcome", description: "ACCEPT/REFUSE and attendance outcomes require a different actor from the requester, current designation or bounded Admin, and effective appointment grant. RESCHEDULE atomically replaces the reservation and returns to PENDING. Failed reports keep the old slot. COMPLETE/NO_SHOW are refused before the scheduled end. No-show never creates another appointment or automatic follow-up. Receipt identity includes actor, operation and canonical payload; replay never duplicates effects.", parameters: [idParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["action", "expectedVersion", "idempotencyKey"], properties: { action: { type: "string", enum: ["ACCEPT", "REFUSE", "CANCEL", "RESCHEDULE", "COMPLETE", "NO_SHOW"] }, startsAt: instant, reason: { type: "string", maxLength: 120, description: "Required for REFUSE/CANCEL/RESCHEDULE/NO_SHOW" }, expectedVersion: version, idempotencyKey: key } } } } }, responses: boundedResponses },
  },
  "/admissions/bookings/{id}/slots": { get: { summary: "Read redacted reschedule slots scoped to one authorized booking", parameters: [idParameter, ...rangeParameters], responses: boundedResponses } },
  "/admissions/bookings/{id}/report": { post: { summary: "Persist a manual interview report once after a realized appointment", description: "Only the still designated responsible evaluator, not the requester. Current version and grants rechecked; text stored redacted under the existing InterviewReport contract. No automatic admission decision. Legacy report writes for Admissions metadata are refused.", parameters: [idParameter], requestBody: { required: true, content: { "application/json": { schema: { type: "object", additionalProperties: false, required: ["expectedVersion", "idempotencyKey", "result", "comment", "recommendation"], properties: { expectedVersion: version, idempotencyKey: key, result: { type: "string", enum: ["FAVORABLE", "FAVORABLE_SOUS_CONDITION", "A_COMPLETER", "DEFAVORABLE", "NON_DECIDE"] }, comment: { type: "string", maxLength: 2000 }, recommendation: { type: "string", maxLength: 1000 }, missingPoints: { type: "string", maxLength: 2000 }, nextAction: { type: "string", maxLength: 120 }, followUpAt: instant } } } } }, responses: { ...boundedResponses, "201": { description: "One report, event, activity, audit, receipt and internal notification per recipient persisted" } } } },
} as const;
