import assert from "node:assert/strict";
import type { AddressInfo } from "node:net";
import test from "node:test";
import { createApplication } from "./synthetic-application.js";
import { AuditService } from "../../src/audit/audit.service.js";
import { SessionService } from "../../src/auth/session.service.js";
import type { Role } from "../../src/auth/auth.types.js";
import { CandidateDocumentService } from "../../src/documents/candidate-document.service.js";
import { LeadService } from "../../src/leads/lead.service.js";
import { UserService } from "../../src/users/user.service.js";

test("runs the 15-step synthetic candidate dossier journey and cleans temporary storage", async (context) => {
  const app = await createApplication(); const users = app.get(UserService); const sessions = app.get(SessionService); const leads = app.get(LeadService); const documents = app.get(CandidateDocumentService); const audit = app.get(AuditService);
  const adviser = users.create({ professionalEmail: "document-adviser@example.invalid", roles: ["ADMISSIONS"], campusId: "campus-a" }, "bootstrap", "adviser"); const manager = users.create({ professionalEmail: "document-manager@example.invalid", roles: ["MANAGER"], campusId: "campus-a" }, "bootstrap", "manager"); const outsider = users.create({ professionalEmail: "document-outsider@example.invalid", roles: ["ADMISSIONS"], campusId: "campus-b" }, "bootstrap", "outsider"); const lead = leads.registerLocalLead({ leadCode: "LD-DOC-E2E", firstName: "Synthetic", lastName: "Candidate", campus: "campus-a", campaign: "Synthetic", educationLevel: "BAC", program: "Program", source: "MANUAL" });
  await app.listen(0, "127.0.0.1"); context.after(async (): Promise<void> => { await documents.cleanup(); await app.close(); }); const address = app.getHttpServer().address() as AddressInfo; const base = `http://127.0.0.1:${address.port}`;
  const token = (userId: string, roles: Role[], campus: string): string => sessions.create(userId, roles, [{ kind: "CAMPUS", id: campus }]).token; const adviserToken = token(adviser.id, ["ADMISSIONS"], "campus-a"); const managerToken = token(manager.id, ["MANAGER"], "campus-a"); const outsiderToken = token(outsider.id, ["ADMISSIONS"], "campus-b"); const headers = (value: string): Record<string, string> => ({ authorization: `Bearer ${value}`, "content-type": "application/json", "x-correlation-id": "document-e2e" });
  const checklistResponse = await fetch(`${base}/leads/${lead.id}/documents/checklist`, { method: "POST", headers: headers(adviserToken), body: JSON.stringify({ admissionLevel: "BAC", program: "Programme synthétique", applicationType: "INITIAL", situation: "ÉTUDIANT" }) }); assert.equal(checklistResponse.status, 201); const checklist = await checklistResponse.json() as Array<{ id: string; documentType: string }>; assert.ok(checklist.length >= 3); const item = checklist[0]!;
  const uploadBody = { checklistItemId: item.id, documentType: item.documentType, originalName: "synthetic.pdf", declaredMime: "application/pdf", contentBase64: Buffer.from("%PDF-1.7\nSynthetic only\n%%EOF").toString("base64") }; const upload = await fetch(`${base}/leads/${lead.id}/documents`, { method: "POST", headers: headers(adviserToken), body: JSON.stringify(uploadBody) }); assert.equal(upload.status, 201); const received = await upload.json() as { id: string; sha256: string; verificationStatus: string }; assert.equal(received.verificationStatus, "À_VÉRIFIER"); assert.match(received.sha256, /^[a-f0-9]{64}$/);
  const center = await fetch(`${base}/notifications`, { headers: headers(adviserToken) }).then((response) => response.json()) as { items: Array<{ type: string }> }; assert.equal(center.items[0]?.type, "DOCUMENT_RECEIVED"); assert.equal((await fetch(`${base}/candidate-documents/${received.id}/verification`, { method: "PATCH", headers: headers(managerToken), body: JSON.stringify({ decision: "REFUSER", reasonCode: "ILLISIBLE" }) })).status, 200);
  const replacement = await fetch(`${base}/leads/${lead.id}/documents`, { method: "POST", headers: headers(adviserToken), body: JSON.stringify({ ...uploadBody, originalName: "replacement.pdf", replacesDocumentId: received.id }) }); assert.equal(replacement.status, 201); const replacementBody = await replacement.json() as { id: string; version: number }; assert.equal(replacementBody.version, 2); assert.equal((await fetch(`${base}/candidate-documents/${replacementBody.id}/verification`, { method: "PATCH", headers: headers(managerToken), body: JSON.stringify({ decision: "VALIDER" }) })).status, 200);
  assert.equal((await fetch(`${base}/candidate-documents/${received.id}`, { headers: headers(outsiderToken) })).status, 404); const history = await fetch(`${base}/candidate-documents/${replacementBody.id}`, { headers: headers(managerToken) }).then((response) => response.json()) as { events: unknown[] }; assert.equal(history.events.length, 2); const dashboard = await fetch(`${base}/candidate-documents/dashboard?page=1&pageSize=25`, { headers: headers(managerToken) }); assert.equal(dashboard.status, 200); const spec = await fetch(`${base}/docs-json`).then((response) => response.json()) as { paths: Record<string, unknown> }; for (const path of ["/leads/{leadId}/documents/checklist", "/leads/{leadId}/documents", "/candidate-documents/{id}/verification", "/candidate-documents/dashboard"]) assert.ok(spec.paths[path]); const auditText = JSON.stringify(audit.list(500)); assert.equal(auditText.includes("synthetic.pdf"), false); assert.equal(auditText.includes(received.sha256), false); await documents.cleanup();
});
