import assert from "node:assert/strict";
import type { AddressInfo } from "node:net";
import test from "node:test";
import { createApplication } from "../../src/application.js";
import { SessionService } from "../../src/auth/session.service.js";
import { LeadService } from "../../src/leads/lead.service.js";

test("demonstrates the code-only telephony API without real call or audio", async (context) => {
  const app = await createApplication(); const sessions = app.get(SessionService); const leads = app.get(LeadService); const lead = leads.registerLocalLead({ leadCode: "LD-TEL-E2E", firstName: "Synthetic", lastName: "Lead", phone: "+212600000148", campus: "campus-a", campaign: "Synthetic", educationLevel: "BAC", program: "Program", source: "MANUAL" }); const admin = sessions.create("admin-e2e", ["SUPER_ADMIN"], [{ kind: "GLOBAL" }]).token; const adviser = sessions.create("adviser-e2e", ["ADMISSIONS"], [{ kind: "CAMPUS", id: "campus-a" }]).token;
  await app.listen(0, "127.0.0.1"); context.after(() => app.close()); const base = `http://127.0.0.1:${(app.getHttpServer().address() as AddressInfo).port}`; const headers = (token: string): Record<string, string> => ({ authorization: `Bearer ${token}`, "content-type": "application/json", "x-correlation-id": "telephony-e2e" });
  const disabled = await fetch(`${base}/leads/${lead.id}/calls`, { method: "POST", headers: headers(adviser), body: JSON.stringify({ idempotencyKey: "e2e-disabled-01" }) }); assert.equal(disabled.status, 503);
  const configured = await fetch(`${base}/telephony/configuration`, { method: "PATCH", headers: headers(admin), body: JSON.stringify({ expectedVersion: 1, mode: "MANUAL_EXTERNAL", clickToCallEnabled: true, inboundEnabled: true, outboundEnabled: true, recordingPolicy: "METADATA_ONLY", maxCallDurationSeconds: 7200 }) }); assert.equal(configured.status, 200);
  const requested = await fetch(`${base}/leads/${lead.id}/calls`, { method: "POST", headers: headers(adviser), body: JSON.stringify({ idempotencyKey: "e2e-outbound-01" }) }); assert.equal(requested.status, 201); const call = await requested.json() as { id: string; maskedPhone: string; externalId: string; requestedAt: string }; assert.equal(call.maskedPhone, "***148"); assert.equal(JSON.stringify(call).includes("+212600000148"), false);
  const afterRequest = (seconds: number): string => new Date(Date.parse(call.requestedAt) + seconds * 1_000).toISOString();
  for (const [state, key, occurredAt] of [["RINGING", "e2e-ringing-01", afterRequest(1)], ["ANSWERED", "e2e-answer-001", afterRequest(6)], ["ENDED", "e2e-ended-0001", afterRequest(36)]] as const) { const response = await fetch(`${base}/calls/${call.id}/events`, { method: "POST", headers: headers(adviser), body: JSON.stringify({ state, idempotencyKey: key, occurredAt }) }); assert.equal(response.status, 201); }
  const detail = await fetch(`${base}/calls/${call.id}`, { headers: headers(adviser) }).then((response) => response.json()) as { state: string; durationSeconds: number }; assert.equal(detail.state, "ENDED"); assert.equal(detail.durationSeconds, 30); const recording = await fetch(`${base}/calls/${call.id}/recording`, { headers: headers(admin) }).then((response) => response.json()) as { recordingId: string; state: string; durationSeconds: number; provider: string; authorizedRoles: string[] }; assert.deepEqual(recording, { recordingId: recording.recordingId, state: "UNAVAILABLE", durationSeconds: 30, provider: "MANUAL_EXTERNAL", authorizedRoles: ["MANAGER", "ADMIN", "SUPER_ADMIN"] });
  assert.equal((await fetch(`${base}/integrations/telephony/webhook`, { method: "POST", headers: headers(admin), body: "{}" })).status, 503); const spec = await fetch(`${base}/docs-json`).then((response) => response.json()) as { paths: Record<string, unknown> }; for (const path of ["/telephony/configuration", "/leads/{leadId}/calls", "/calls/{callId}/events", "/calls/{callId}/recording", "/integrations/telephony/webhook"]) assert.ok(spec.paths[path]);
});
