import assert from "node:assert/strict";
import test from "node:test";
import { AuditService } from "../src/audit/audit.service.js";
import type { Principal } from "../src/auth/auth.types.js";
import { CandidateDocumentService } from "../src/documents/candidate-document.service.js";
import { LocalTemporaryDocumentStorageAdapter } from "../src/documents/document-storage.adapter.js";
import { LeadService } from "../src/leads/lead.service.js";
import { NotificationService } from "../src/notifications/notification.service.js";
import type { LeadRecord } from "../src/leads/lead.service.js";

const code = (value: string) => (error: unknown): boolean => JSON.stringify((error as { getResponse(): unknown }).getResponse()).includes(value);
const principal = (userId: string, roles: Principal["roles"], campus = "campus-a"): Principal => ({ userId, roles, scopes: roles.some((role) => role === "ADMIN" || role === "SUPER_ADMIN") ? [{ kind: "GLOBAL" }] : [{ kind: "CAMPUS", id: campus }], sessionId: `session-${userId}` });
const pdf = Buffer.from("%PDF-1.7\nSynthetic candidate document only\n%%EOF").toString("base64");

interface Fixture { audit: AuditService; leads: LeadService; notifications: NotificationService; storage: LocalTemporaryDocumentStorageAdapter; service: CandidateDocumentService; lead: LeadRecord }
function fixture(scanner = true): Fixture { const audit = new AuditService(); const leads = new LeadService(audit); const notifications = new NotificationService(audit); const storage = new LocalTemporaryDocumentStorageAdapter(scanner, 2048); const service = new CandidateDocumentService(audit, leads, notifications, storage); const lead = leads.registerLocalLead({ id: "00000000-0000-4000-8000-000000000147", leadCode: "LD-SYN-147", firstName: "Synthetic", lastName: "Candidate", campus: "campus-a", campaign: "Synthetic", educationLevel: "BAC", program: "Program", source: "MANUAL" }); return { audit, leads, notifications, storage, service, lead }; }

test("runs the complete synthetic checklist, refusal, replacement and validation journey", async (context) => {
  const { audit, notifications, service, lead } = fixture(); context.after(() => service.cleanup()); const adviser = principal("adviser-synthetic", ["ADMISSIONS"]); const manager = principal("manager-synthetic", ["MANAGER"]);
  const checklist = service.generateChecklist(lead.id, { admissionLevel: "BAC+3", program: "Programme synthétique", applicationType: "INITIAL", situation: "SALARIÉ", scholarship: true }, adviser, "checklist"); assert.equal(checklist.length, 6); assert.equal(checklist.every((item) => item.state === "MANQUANT"), true); assert.deepEqual(service.generateChecklist(lead.id, { admissionLevel: "OTHER", program: "Other", applicationType: "OTHER", situation: "OTHER" }, adviser, "replay").map((item) => item.id), checklist.map((item) => item.id));
  const item = checklist.find((candidate) => candidate.documentType === "BACCALAUREAT")!;
  for (const invalid of [{ originalName: "../escape.pdf", declaredMime: "application/pdf", contentBase64: pdf }, { originalName: "candidate.exe", declaredMime: "application/octet-stream", contentBase64: pdf }, { originalName: "candidate.pdf", declaredMime: "image/png", contentBase64: pdf }, { originalName: "candidate.pdf", declaredMime: "application/pdf", contentBase64: Buffer.from("MZ executable").toString("base64") }]) await assert.rejects(service.upload(lead.id, { checklistItemId: item.id, documentType: item.documentType, ...invalid }, adviser, "invalid"), code("document_"));
  const received = await service.upload(lead.id, { checklistItemId: item.id, documentType: item.documentType, originalName: "synthetic.pdf", declaredMime: "application/pdf", contentBase64: pdf }, adviser, "received"); assert.equal(received.verificationStatus, "À_VÉRIFIER"); assert.match(received.sha256, /^[a-f0-9]{64}$/); assert.equal(received.sanitizedFileName.includes("synthetic"), false); assert.equal(notifications.list(adviser, 1, 25).items[0]?.type, "DOCUMENT_RECEIVED");
  assert.throws(() => service.verify(received.id, { decision: "REFUSER" }, manager, "missing-reason"), code("document_decision_invalid")); const refused = service.verify(received.id, { decision: "REFUSER", reasonCode: "ILLISIBLE" }, manager, "refused"); assert.equal(refused.verificationStatus, "REFUSÉ"); assert.throws(() => service.verify(received.id, { decision: "VALIDER" }, manager, "immutable"), code("document_transition_invalid"));
  const replacement = await service.upload(lead.id, { checklistItemId: item.id, documentType: item.documentType, originalName: "replacement.pdf", declaredMime: "application/pdf", contentBase64: pdf, replacesDocumentId: received.id }, adviser, "replacement"); assert.equal(replacement.version, 2); assert.equal(service.detail(received.id, adviser).document.verificationStatus, "REMPLACÉ"); const validated = service.verify(replacement.id, { decision: "VALIDER" }, manager, "validated"); assert.equal(validated.verificationStatus, "VALIDÉ"); assert.equal(service.checklist(lead.id, adviser).find((candidate) => candidate.id === item.id)?.state, "VALIDÉ");
  const events = service.detail(replacement.id, manager).events; assert.deepEqual(events.map((event) => event.eventType), ["DOCUMENT_REPLACEMENT_RECEIVED", "DOCUMENT_VALIDÉ"]); const dashboard = service.dashboard({ page: 1, pageSize: 25 }, manager); assert.equal(dashboard.counters.complete, 0); assert.equal(dashboard.aggregateExport.incomplete, 1); const auditJson = JSON.stringify(audit.list(200)); assert.equal(auditJson.includes("synthetic.pdf"), false); assert.equal(auditJson.includes(received.sha256), false);
  assert.equal(service.dashboard({ page: 1, pageSize: 25, program: "program", educationLevel: "bac", campus: "campus-a", assignedToId: "absent" }, manager).total, 0);
  assert.equal(service.dashboard({ page: 1, pageSize: 25, documentType: "BACCALAUREAT", state: "COMPLET" }, manager).total, 1);
  assert.equal(service.dashboard({ page: 1, pageSize: 25, view: "MINE" }, adviser).total, 0);
  assert.throws(() => service.dashboard({ page: 1, pageSize: 25, state: "UNKNOWN" }, manager), code("document_state_filter_invalid"));
});

test("fails closed for campus IDOR, unavailable scanner, unsafe inputs and unauthorized verification", async (context) => {
  const { service, lead } = fixture(); context.after(() => service.cleanup()); const adviser = principal("adviser", ["ADMISSIONS"]); const outsider = principal("outsider", ["ADMISSIONS"], "campus-b"); const checklist = service.generateChecklist(lead.id, { admissionLevel: "BAC", program: "Programme", applicationType: "INITIAL", situation: "ÉTUDIANT" }, adviser, "checklist"); const item = checklist[0]!;
  assert.throws(() => service.checklist(lead.id, outsider), code("lead_not_found")); const received = await service.upload(lead.id, { checklistItemId: item.id, documentType: item.documentType, originalName: "synthetic.pdf", declaredMime: "application/pdf", contentBase64: pdf }, adviser, "upload"); assert.throws(() => service.verify(received.id, { decision: "VALIDER" }, adviser, "forbidden"), code("document_verification_forbidden")); assert.throws(() => service.detail(received.id, outsider), code("lead_not_found"));
  const unavailable = fixture(false); context.after(() => unavailable.service.cleanup()); const unavailableItem = unavailable.service.generateChecklist(unavailable.lead.id, { admissionLevel: "BAC", program: "Programme", applicationType: "INITIAL", situation: "ÉTUDIANT" }, adviser, "checklist")[0]!; await assert.rejects(unavailable.service.upload(unavailable.lead.id, { checklistItemId: unavailableItem.id, documentType: unavailableItem.documentType, originalName: "synthetic.pdf", declaredMime: "application/pdf", contentBase64: pdf }, adviser, "upload"), code("document_antivirus_unavailable"));
});
