import "reflect-metadata";
import assert from "node:assert/strict";
import test from "node:test";
import { AuditService } from "../src/audit/audit.service.js";
import { SessionService } from "../src/auth/session.service.js";
import type { AuthenticatedRequest, Principal } from "../src/auth/auth.types.js";
import { UserService } from "../src/users/user.service.js";
import { LeadService } from "../src/leads/lead.service.js";
import { NotificationService } from "../src/notifications/notification.service.js";
import { AppointmentService } from "../src/appointments/appointment.service.js";
import { ChatService } from "../src/chat/chat.service.js";
import { FollowUpService } from "../src/follow-up/follow-up.service.js";
import { TelephonyService } from "../src/telephony/telephony.service.js";
import { DynamicResourceLocator } from "../src/permissions/dynamic-locator.js";
import { routePermissions } from "../src/permissions/dynamic-routes.js";

test("CRMY-169 indirect resource IDs come from owning services; cross-campus follow-ups are not disclosed", (t) => {
  const audit = new AuditService(), users = new UserService(new SessionService(), audit), leads = new LeadService(audit), notifications = new NotificationService(audit);
  const author = users.create({ professionalEmail: "author@example.invalid", roles: ["MANAGER"] }, "synthetic", "synthetic");
  const colleague = users.create({ professionalEmail: "colleague@example.invalid", roles: ["ADMISSIONS"] }, "synthetic", "synthetic");
  const principal: Principal = { userId: author.id, roles: ["MANAGER"], sessionId: "synthetic", scopes: [{ kind: "CAMPUS", id: "SYNTHETIC" }] };
  const lead = leads.registerLocalLead({ leadCode: "LD-2026-ABCDEF12", firstName: "Lead", lastName: "Synthétique", campus: "SYNTHETIC", source: "TEST", campaign: "TEST", program: "TEST", educationLevel: "BAC", assignedToId: author.id });
  const appointments = new AppointmentService(leads, notifications, audit), chat = new ChatService(audit, users, leads, notifications), followUps = new FollowUpService(leads, notifications, audit), telephony = new TelephonyService(audit, leads);
  const locator = new DynamicResourceLocator(appointments, chat, followUps, telephony);
  const request = (params: Record<string, string>, body: unknown = {}): AuthenticatedRequest => ({ params, body, principal } as AuthenticatedRequest);
  const followUp = followUps.schedule(lead.id, { dueAt: "2099-01-01T12:00:00Z", reason: "Synthétique" }, principal, "synthetic");
  assert.deepEqual(locator.leadIds("FollowUpController", "decide", request({ id: followUp.id })), [lead.id]);
  assert.deepEqual(followUps.list({ ...principal, scopes: [{ kind: "CAMPUS", id: "OTHER" }] }), []);
  assert.throws(() => followUps.decide(followUp.id, { action: "COMPLETE", reason: "Synthétique", expectedVersion: 1 }, { ...principal, scopes: [{ kind: "CAMPUS", id: "OTHER" }] }, "synthetic"));
  assert.equal(followUps.list(principal)[0]?.state, "SCHEDULED");
  assert.throws(() => locator.leadIds("FollowUpController", "decide", request({ id: "missing" })));
  const appointment = appointments.create(lead.id, { type: "APPEL_INFORMATION", mode: "DISTANCIEL_NON_CONNECTE", startsAt: "2099-01-02T12:00:00Z", durationMinutes: 30, idempotencyKey: "synthetic-locator" }, principal, "synthetic");
  assert.deepEqual(locator.leadIds("AppointmentController", "detail", request({ id: appointment.id })), [lead.id]);
  assert.throws(() => appointments.permissionLeadId("missing"));
  const conversation = chat.createConversation(principal, { type: "DIRECT", participantIds: [colleague.id], leadCode: lead.leadCode }, "synthetic");
  const message = chat.postMessage(conversation.id, principal, { content: "Message synthétique", clientMessageId: "synthetic-locator" }, "synthetic");
  assert.deepEqual(locator.leadIds("ChatController", "convertToActivity", request({ messageId: message.id })), [lead.id]);
  assert.deepEqual(routePermissions("ChatController", "convertToActivity"), ["chat.use", "interaction.create"]);
  assert.throws(() => chat.permissionLeadId(message.id, { ...principal, userId: "outsider" }));
  const unlinked = chat.createConversation(principal, { type: "DIRECT", participantIds: [colleague.id] }, "synthetic");
  const unlinkedMessage = chat.postMessage(unlinked.id, principal, { content: "Synthétique", clientMessageId: "synthetic-unlinked" }, "synthetic");
  assert.throws(() => chat.permissionLeadId(unlinkedMessage.id, principal));
  assert.throws(() => telephony.permissionLeadId("missing"));
  t.mock.method(telephony, "permissionLeadId", () => lead.id);
  assert.deepEqual(locator.leadIds("TelephonyController", "detail", request({ callId: "synthetic-call" })), [lead.id]);
  assert.deepEqual(locator.leadIds("TelephonyController", "associate", request({ callId: "synthetic-call" }, { leadId: "target" })), [lead.id, "target"]);
  assert.throws(() => locator.leadIds("TelephonyController", "associate", request({ callId: "synthetic-call" }, {})));
  assert.deepEqual(locator.leadIds("LeadController", "list", request({})), []);
});
