import assert from "node:assert/strict"; import test from "node:test"; import { AuditService } from "../src/audit/audit.service.js"; import type { Principal } from "../src/auth/auth.types.js"; import { FollowUpService } from "../src/follow-up/follow-up.service.js"; import { LeadService, type LeadRecord } from "../src/leads/lead.service.js"; import { NotificationService } from "../src/notifications/notification.service.js";
import { ConflictException } from "@nestjs/common";
import type { FollowUpRecord } from "../src/follow-up/follow-up.service.js";
const adviser: Principal = { userId: "00000000-0000-4000-8000-000000000048", roles: ["ADMISSIONS"], scopes: [{ kind: "GLOBAL" }], sessionId: "synthetic" }; const manager: Principal = { ...adviser, userId: "00000000-0000-4000-8000-000000000049", roles: ["MANAGER"] }; const code=(value:string)=>(error:unknown): boolean=>JSON.stringify((error as {getResponse():unknown}).getResponse()).includes(value);
function setup(): { audit: AuditService; leads: LeadService; notifications: NotificationService; service: FollowUpService; lead: LeadRecord } { const audit=new AuditService(); const leads=new LeadService(audit); const notifications=new NotificationService(audit); const service=new FollowUpService(leads,notifications,audit); const lead=leads.registerLocalLead({leadCode:"LD-FOLLOW",firstName:"Alex",lastName:"Synthétique",campus:"Test",campaign:"Test",educationLevel:"Test",program:"Test",source:"TEST",assignedToId:adviser.userId}); return {audit,leads,notifications,service,lead}; }
test("schedules, emits one due notification, postpones and completes",()=>{ const {service,notifications,lead,leads}=setup(); const item=service.schedule(lead.id,{dueAt:"2099-01-01T10:00:00.000Z",reason:"Relance synthétique"},adviser,"corr"); assert.equal(leads.getLead(lead.id,adviser,"read").nextActionAt,item.dueAt); assert.deepEqual(service.notifyDue(new Date("2099-01-01T10:01:00.000Z")),{due:1,notifications:1}); assert.deepEqual(service.notifyDue(new Date("2099-01-01T10:02:00.000Z")),{due:0,notifications:0}); const notification=notifications.list(adviser,1,25); assert.equal(notification.total,1); assert.equal(notification.items[0]?.href,`/leads/${lead.id}/follow-ups`); const postponed=service.decide(item.id,{action:"POSTPONE",dueAt:"2099-01-02T10:00:00.000Z",reason:"Report contrôlé",expectedVersion:2},adviser,"postpone"); assert.equal(postponed.state,"SCHEDULED"); const completed=service.decide(item.id,{action:"COMPLETE",reason:"Traitée",expectedVersion:3},adviser,"complete"); assert.equal(completed.state,"COMPLETED"); assert.equal(leads.getLead(lead.id,adviser,"read2").nextActionAt,undefined); });
test("refuses IDOR, duplicates and concurrent decisions",()=>{ const {service,lead}=setup(); const item=service.schedule(lead.id,{dueAt:"2099-01-01T10:00:00.000Z",reason:"Test"},adviser,"corr"); assert.throws(()=>service.schedule(lead.id,{dueAt:"2099-01-02T10:00:00.000Z",reason:"Test"},adviser,"dup"),code("follow_up_pending")); assert.throws(()=>service.decide(item.id,{action:"COMPLETE",reason:"No",expectedVersion:1},{...adviser,userId:"other"},"idor"),code("follow_up_forbidden")); assert.throws(()=>service.decide(item.id,{action:"COMPLETE",reason:"No",expectedVersion:2},manager,"stale"),code("follow_up_concurrent")); });
test("persistent due processing trusts the atomic repository and never queues a second notification", async()=>{ const {audit,leads,notifications,lead}=setup(); const due={id:"00000000-0000-4000-8000-000000000098",leadId:lead.id,ownerId:adviser.userId,dueAt:"2026-09-16T10:00:00.000Z",state:"DUE" as const,reason:"Échéance synthétique",version:2,createdAt:"2026-09-16T09:00:00.000Z",updatedAt:"2026-09-16T10:00:00.000Z"}; const persistence={enabled:true,markDue:():Promise<{due:number;notifications:number}>=>Promise.resolve({due:0,notifications:1}),snapshot:():Promise<(typeof due)[]>=>Promise.resolve([due])}; notifications.create=():never=>{throw new Error("notification_must_commit_in_repository");}; notifications.flush=():Promise<void>=>Promise.reject(new Error("no_post_commit_queue")); const service=new FollowUpService(leads,notifications,audit,persistence as never); assert.deepEqual(await service.notifyDueForApi(new Date(due.dueAt)),{due:0,notifications:1}); assert.equal(service.permissionLeadId(due.id),lead.id); });

test("a postponed in-memory reminder notifies again for its next occurrence",()=>{ const {service,notifications,lead}=setup(); const item=service.schedule(lead.id,{dueAt:"2099-01-01T10:00:00.000Z",reason:"Relance synthétique"},adviser,"corr"); service.notifyDue(new Date("2099-01-01T10:01:00.000Z")); service.decide(item.id,{action:"POSTPONE",dueAt:"2099-01-02T10:00:00.000Z",reason:"Report contrôlé",expectedVersion:2},adviser,"postpone"); assert.deepEqual(service.notifyDue(new Date("2099-01-02T10:01:00.000Z")),{due:1,notifications:1}); assert.deepEqual(service.notifyDue(new Date("2099-01-02T10:02:00.000Z")),{due:0,notifications:0}); assert.equal(notifications.list(adviser,1,25).total,2); });

test("persistent schedule and decision preserve the original conflict without querying an aborted ambient transaction", async () => {
  for (const operation of ["schedule", "decide"] as const) {
    const { audit, leads, notifications, lead } = setup();
    const current: FollowUpRecord = { id: "00000000-0000-4000-8000-000000000098", leadId: lead.id, ownerId: adviser.userId, dueAt: "2099-01-01T10:00:00.000Z", state: "SCHEDULED", reason: "Synthétique", version: 1, createdAt: "2098-01-01T10:00:00.000Z", updatedAt: "2098-01-01T10:00:00.000Z" };
    const original = new ConflictException({ code: "follow_up_concurrent" }); let aborted = false; let reads = 0;
    const fail = (): Promise<never> => { aborted = true; return Promise.reject(original); };
    const persistence = {
      enabled: true, fingerprint: (): string => "synthetic-fingerprint", findReplay: (): Promise<undefined> => Promise.resolve(undefined),
      snapshot: (): Promise<FollowUpRecord[]> => { reads += 1; return aborted ? Promise.reject(new Error("synthetic_transaction_aborted")) : Promise.resolve(operation === "decide" ? [current] : []); },
      schedule: fail, decide: fail,
    };
    leads.getLeadForApi = (): Promise<LeadRecord> => Promise.resolve(lead);
    leads.refreshReportingForApi = (): Promise<void> => Promise.reject(new Error("synthetic_transaction_aborted"));
    const service = new FollowUpService(leads, notifications, audit, persistence as never);
    const mutation = operation === "schedule"
      ? service.scheduleForApi(lead.id, { dueAt: current.dueAt, reason: current.reason, idempotencyKey: "follow-up-abort-schedule" }, adviser, "abort-schedule")
      : service.decideForApi(current.id, { action: "CANCEL", reason: "Synthétique", expectedVersion: 1, idempotencyKey: "follow-up-abort-decision" }, adviser, "abort-decision");
    await assert.rejects(() => mutation, (error: unknown) => error === original); assert.equal(reads, 1);
  }
});
