import assert from "node:assert/strict";
import { createHmac } from "node:crypto";
import test from "node:test";
import { AuditService } from "../src/audit/audit.service.js";
import type { AuthenticatedRequest, Principal } from "../src/auth/auth.types.js";
import { LeadService } from "../src/leads/lead.service.js";
import { TelephonyController } from "../src/telephony/telephony.controller.js";
import { DisabledTelephonyAdapter, ManualExternalTelephonyAdapter, SyntheticTelephonyAdapter } from "../src/telephony/telephony.adapter.js";
import { TelephonyService } from "../src/telephony/telephony.service.js";

const code = (expected: string) => (error: unknown): boolean => JSON.stringify((error as { getResponse(): unknown }).getResponse()).includes(expected);
const principal = (userId: string, roles: Principal["roles"], campus = "campus-a"): Principal => ({ userId, roles, scopes: roles.includes("SUPER_ADMIN") ? [{ kind: "GLOBAL" }] : [{ kind: "CAMPUS", id: campus }], sessionId: `session-${userId}` });
function fixture(): { audit: AuditService; leads: LeadService; service: TelephonyService; first: ReturnType<LeadService["registerLocalLead"]> } { const audit = new AuditService(); const leads = new LeadService(audit); const service = new TelephonyService(audit, leads); const first = leads.registerLocalLead({ id: "00000000-0000-4000-8000-000000000148", leadCode: "LD-TEL-148", firstName: "Lead", lastName: "Synthetic", phone: "+212600000148", campus: "campus-a", campaign: "Synthetic", educationLevel: "BAC", program: "Program", source: "MANUAL" }); return { audit, leads, service, first }; }
const configure = (service: TelephonyService, admin: Principal, mode: "MANUAL_EXTERNAL" | "COOVOX" | "LINPHONE" = "MANUAL_EXTERNAL"): ReturnType<TelephonyService["configure"]> => service.configure({ expectedVersion: service.configuration().version, mode, clickToCallEnabled: true, inboundEnabled: true, outboundEnabled: true, recordingPolicy: "METADATA_ONLY", maxCallDurationSeconds: 7200, secretReference: "ref:future-provider" }, admin, `config-${mode}`);

test("executes the complete outbound lifecycle, idempotence, duration and append-only timeline", () => {
  const { audit, leads, service, first } = fixture(); const admin = principal("admin-synthetic", ["SUPER_ADMIN"]); const adviser = principal("adviser-synthetic", ["ADMISSIONS"]); configure(service, admin);
  const call = service.initiate(first.id, { idempotencyKey: "outbound-0001", followUpComment: "Synthétique", nextActionAt: "2026-08-26T10:00:00Z" }, adviser, "outbound"); assert.equal(call.state, "REQUESTED"); assert.equal(call.maskedPhone, "***148"); assert.equal(call.phoneFingerprint.length, 64); assert.equal(call.recording.state, "UNAVAILABLE"); assert.equal(service.initiate(first.id, { idempotencyKey: "outbound-0001" }, adviser, "replay").id, call.id);
  const ringing = service.receiveEvent(call.id, { idempotencyKey: "event-ring-0001", state: "RINGING", occurredAt: "2026-08-25T09:00:00Z" }, adviser, "ring"); assert.equal(ringing.state, "RINGING"); const answered = service.receiveEvent(call.id, { idempotencyKey: "event-answer-01", state: "ANSWERED", occurredAt: "2026-08-25T09:00:10Z" }, adviser, "answer"); assert.equal(answered.answeredAt, "2026-08-25T09:00:10.000Z"); const ended = service.receiveEvent(call.id, { idempotencyKey: "event-ended-001", state: "ENDED", occurredAt: "2026-08-25T09:01:10Z" }, adviser, "end"); assert.equal(ended.durationSeconds, 60); assert.equal(ended.events.length, 4); assert.equal(service.receiveEvent(call.id, { idempotencyKey: "event-ended-001", state: "ENDED" }, adviser, "replay").events.length, 4);
  assert.throws(() => service.receiveEvent(call.id, { idempotencyKey: "event-invalid-01", state: "RINGING", occurredAt: "2026-08-25T09:02:00Z" }, adviser, "invalid"), code("telephony_transition_invalid")); const corrected = service.compensate(call.id, { idempotencyKey: "compensate-0001", reasonCode: "WRONG_RESULT" }, admin, "correct"); assert.equal(corrected.events.at(-1)?.eventType, "COMPENSATION"); assert.equal(leads.timeline(first.id, adviser).some((event) => event.result === "CALL_ENDED"), true);
  const text = JSON.stringify(audit.list(200)); assert.equal(text.includes("+212600000148"), false); assert.equal(text.includes("Synthétique"), false);
});

test("fails closed for disabled real providers, impossible order, thresholds and RBAC", () => {
  const { service, first } = fixture(); const admin = principal("admin", ["SUPER_ADMIN"]); const adviser = principal("adviser", ["ADMISSIONS"]); const outsider = principal("outsider", ["ADMISSIONS"], "campus-b"); const auditor = principal("auditor", ["AUDITOR"]);
  assert.throws(() => service.initiate(first.id, { idempotencyKey: "disabled-0001" }, adviser, "disabled"), code("telephony_provider_disabled")); configure(service, admin, "COOVOX"); assert.throws(() => service.initiate(first.id, { idempotencyKey: "coovox-000001" }, adviser, "coovox"), code("provider_not_configured")); configure(service, admin, "LINPHONE"); assert.throws(() => service.initiate(first.id, { idempotencyKey: "linphone-00001" }, adviser, "linphone"), code("provider_not_configured")); configure(service, admin);
  assert.throws(() => service.initiate(first.id, { idempotencyKey: "idor-0000001" }, outsider, "idor"), code("lead_not_found")); assert.throws(() => service.queue(auditor), code("telephony_role_forbidden")); assert.throws(() => service.configure({ expectedVersion: 4, mode: "DISABLED", recordingPolicy: "DISABLED", maxCallDurationSeconds: 7200 }, adviser, "forbidden"), code("telephony_configuration_forbidden")); assert.throws(() => service.configure({ expectedVersion: service.configuration().version, mode: "MANUAL_EXTERNAL", recordingPolicy: "DISABLED", maxCallDurationSeconds: 1 }, admin, "duration"), code("telephony_duration_threshold_invalid")); assert.throws(() => service.configure({ expectedVersion: service.configuration().version, mode: "MANUAL_EXTERNAL", recordingPolicy: "DISABLED", maxCallDurationSeconds: 7200, secretReference: "token=not-allowed" }, admin, "secret"), code("telephony_secret_reference_invalid"));
  const call = service.initiate(first.id, { idempotencyKey: "ordered-000001" }, adviser, "call"); service.receiveEvent(call.id, { idempotencyKey: "ordered-ring-01", state: "RINGING", occurredAt: "2026-08-25T10:00:00Z" }, adviser, "ring"); assert.throws(() => service.receiveEvent(call.id, { idempotencyKey: "ordered-old-001", state: "ANSWERED", occurredAt: "2026-08-25T09:00:00Z" }, adviser, "old"), code("telephony_event_out_of_order")); assert.throws(() => service.receiveEvent(call.id, { idempotencyKey: "ordered-ring-01", state: "ANSWERED" }, adviser, "conflict"), code("telephony_event_idempotency_conflict")); assert.throws(() => service.compensate(call.id, { idempotencyKey: "forbidden-comp-1", reasonCode: "WRONG_RESULT" }, adviser, "comp"), code("telephony_compensation_forbidden"));
});

test("matches inbound calls uniquely, queues collisions and requires a human confirmation", () => {
  const { service, leads, first } = fixture(); const admin = principal("manager", ["SUPER_ADMIN"]); const adviser = principal("adviser", ["ADMISSIONS"]); configure(service, admin);
  const unique = service.ingestSyntheticIncoming({ provider: "MANUAL_EXTERNAL", externalId: "incoming-unique", phone: "+212600000148", idempotencyKey: "incoming-unique-1", occurredAt: "2026-08-25T11:00:00Z" }, adviser, "unique"); assert.equal(unique.leadId, first.id); assert.equal(unique.matchState, "MATCHED");
  leads.registerLocalLead({ leadCode: "LD-TEL-DUP", firstName: "Other", lastName: "Synthetic", phone: "+212600000148", campus: "campus-a", campaign: "Synthetic", educationLevel: "BAC", program: "Program", source: "MANUAL" }); const collision = service.ingestSyntheticIncoming({ provider: "MANUAL_EXTERNAL", externalId: "incoming-collision", phone: "+212600000148", idempotencyKey: "incoming-collide", occurredAt: "2026-08-25T11:05:00Z" }, adviser, "collision"); assert.equal(collision.matchState, "AMBIGUOUS"); assert.equal(service.queue(adviser).toVerify.length, 1); const linked = service.confirmAssociation(collision.id, first.id, admin, "confirm"); assert.equal(linked.matchState, "CONFIRMED"); assert.throws(() => service.confirmAssociation(collision.id, first.id, admin, "again"), code("telephony_association_already_resolved"));
  const absent = service.ingestSyntheticIncoming({ provider: "MANUAL_EXTERNAL", externalId: "incoming-absent", phone: "+212699999999", idempotencyKey: "incoming-absent-1", occurredAt: "2026-08-25T11:10:00Z" }, adviser, "absent"); assert.equal(absent.matchState, "UNMATCHED"); service.receiveEvent(absent.id, { idempotencyKey: "absent-ring-0001", state: "RINGING", occurredAt: "2026-08-25T11:10:01Z" }, adviser, "ring"); service.receiveEvent(absent.id, { idempotencyKey: "absent-missed-01", state: "MISSED", occurredAt: "2026-08-25T11:10:02Z" }, adviser, "missed"); assert.equal(service.queue(adviser).missed.length, 1); assert.equal(service.recording(unique.id, admin, "recording").state, "UNAVAILABLE"); assert.throws(() => service.recording(unique.id, adviser, "denied"), code("recording_not_found"));
});

test("keeps webhook disabled while testing synthetic HMAC and adapter contracts", () => {
  const { service } = fixture(); const payload = JSON.stringify({ event: "synthetic" }); const timestamp = "1787644800"; const secret = "synthetic-telephony-secret"; const signature = `sha256=${createHmac("sha256", secret).update(`${timestamp}.${payload}`).digest("hex")}`; assert.equal(service.verifySyntheticSignature(payload, timestamp, signature, secret), true); assert.equal(service.verifySyntheticSignature(payload, timestamp, signature.replace(/.$/, "0"), secret), false); assert.equal(service.webhookStatus().enabled, false); assert.throws(() => service.rejectRealWebhook(), code("telephony_webhook_disabled"));
  const manual = new ManualExternalTelephonyAdapter(); const receipt = manual.initiate({ direction: "OUTBOUND", phoneFingerprint: "f".repeat(64), correlationId: "adapter" }); assert.equal(manual.state(receipt.externalId).configured, true); assert.equal(manual.cancel(receipt.externalId).accepted, true); const synthetic = new SyntheticTelephonyAdapter(); assert.match(synthetic.initiate({ direction: "OUTBOUND", phoneFingerprint: "f".repeat(64), correlationId: "synthetic" }).externalId, /^synthetic-/); for (const provider of ["COOVOX", "LINPHONE"] as const) { const disabled = new DisabledTelephonyAdapter(provider); assert.equal(disabled.available, false); assert.throws(() => disabled.cancel("opaque"), code("provider_not_configured")); }
});

test("exposes controller contracts and rejects missing principals", () => {
  const { service } = fixture(); const controller = new TelephonyController(service); const request = (value?: Principal): AuthenticatedRequest => ({ principal: value, header: () => "controller-correlation" }) as unknown as AuthenticatedRequest; assert.throws(() => controller.queue(request()), code("principal_missing")); assert.deepEqual(controller.webhookStatus(), { enabled: false, reason: "secure_configuration_required" }); assert.throws(() => controller.webhook(), code("telephony_webhook_disabled"));
});
